### ISSUE TITLE
[SuperEditor] - Caret overlay breaks with component padding

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1001]
During some experimentation in a client's app, we added some padding inside of `TextWithHintComponent` and it caused the document's caret overlay to place the caret at the wrong location. The caret appeared too far up. It's as if the component's padding pushed the content down, but the caret stayed at its original offset.

We should figure out why adding padding inside of a component breaks the positioning of the overlay caret, and then adjust the overlay caret, or the document offset calculations, so that this doesn't happen.

**Comment by angelosilvestre** [comment]
@matthew-carroll Does this app happen to have a `Scaffold` with `resizeToAvoidBottomInset` set to `false`?

While I was investigating https://github.com/superlistapp/super_editor/issues/893, I added an `Overlay` to `SuperEditor` and I noticed the same issue. The cause is that we have a `Padding` around the touch controls, for both Android and iOS:

https://github.com/superlistapp/super_editor/blob/d8efa9c6101bd6c458639b9bb9d4e15a2fa8c261/super_editor/lib/src/default_editor/document_gestures_touch_android.dart#L1148-L1158

If the `Overlay` where this widget is displayed already have a `Padding` using the `MediaQuery.of(context).viewInsets.bottom`, we end up with a duplicated padding.

In the "normal" cases, where the `Scaffold` has `resizeToAvoidBottomInset` set to `true`, `MediaQuery.of(context).viewInsets.bottom` is always zero, so this `Padding` has no effect.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros can you check the details of @angelosilvestre investigation with regard to Superlist's `Scaffold` setup?

**Comment by angelosilvestre** [comment]
@miguelcmedeiros Did you have a chance to take a look at my comment?

**Comment by miguelcmedeiros** [comment]
@angelosilvestre missed this one...

In Superlist `resizeToAvoidBottomInset` is not set, so it's true by default.

**Comment by angelosilvestre** [comment]
@matthew-carroll @miguelcmedeiros Is this still happening? I couldn't reproduce it anymore.

**Comment by miguelcmedeiros** [comment]
I can confirm that it's not an issue anymore for us as well.
