### ISSUE TITLE
[SuperEditor] Caret overlay is not updated when document layout changes due to animations

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1022]
Steps to reproduce:
* Run the demo app
* Change the `build` method of `TaskComponent` so that it will animate in a subtitle when the node has selection:
```dart
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.only(left: 16, right: 4),
              child: Checkbox(
                value: widget.viewModel.isComplete,
                onChanged: (newValue) {
                  widget.viewModel.setComplete(newValue!);
                },
              ),
            ),
            Expanded(
              child: TextComponent(
                key: _textKey,
                text: widget.viewModel.text,
                textStyleBuilder: (attributions) {
                  // Show a strikethrough across the entire task if it's complete.
                  final style = widget.viewModel.textStyleBuilder(attributions);
                  return widget.viewModel.isComplete
                      ? style.copyWith(
                          decoration: style.decoration == null
                              ? TextDecoration.lineThrough
                              : TextDecoration.combine([
                                  TextDecoration.lineThrough,
                                  style.decoration!
                                ]),
                        )
                      : style;
                },
                textSelection: widget.viewModel.selection,
                selectionColor: widget.viewModel.selectionColor,
                highlightWhenEmpty: widget.viewModel.highlightWhenEmpty,
                showDebugPaint: widget.showDebugPaint,
              ),
            ),
          ],
        ),
        AnimatedSize(
          duration: const Duration(milliseconds: 100),
          child: widget.viewModel.selection != null
              ? const SizedBox(
                  height: 40,
                  child: Text('some metadata'),
                )
              : const SizedBox.shrink(),
        ),
      ],
    );
  }
```
* Move the selection downwards direction

Expected: the caret is painted in the correct place
Actual: the caret is painted where it was expected to be, if there was no subtitle

https://user-images.githubusercontent.com/31278849/217527882-2707112d-5c3b-478e-91d7-f6c2231085c2.mov

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre I'm gonna take over this ticket because we're gonna need to make some deep alterations to the document layout.

**Comment by matthew-carroll** [comment]
The problem we're dealing with in this ticket is that, in Flutter, child size changes don't trigger rebuilds for ancestors. They do trigger re-layout for some ancestors, but not widget rebuilds.

We need the document layers to rebuild their widget tree when the document changes layout because the layers are likely to inspect the document layout and make positioning decisions based on that document layout inspection.

My plan to resolve this has two steps:

First, I'm going to create a proof of concept where we use `SizeChangedLayoutNotifier` to notify `SuperEditor` whenever any of its document layout changes size. Then `SuperEditor` will explicitly invalidate the layers on top of the document, causing them to rebuild.

This first approach has the downside that we're always 1 frame behind on the document layers.

If the proof of concept solves the fundamental problem, then I'll build a custom `RenderObject` that runs a build phase during its layout phase, in response to something else changing size. 

Such a `RenderObject` doesn't work in general, because if this new `RenderObject` runs layout before the thing it's listening to, then we'll either still end up a frame behind, or we'll try to invalidate layout after we've laid out, which would cause Flutter to blow up. But, if we use this new `RenderObject` tactically, by making sure it appears AFTER the document layout in the widget tree, then it will always run layout after the document, allowing us to rebuild the layer widgets during the layout phase, which saves us from the extra frame problem.

**Comment by matthew-carroll** [comment]
Here's a Flutter issue for fundamental limitations related to this work: https://github.com/flutter/flutter/issues/123305
