### ISSUE TITLE
[Super Editor] Selection property of DocumentComposer become null when clicking on the editor toolbar

### ISSUE THREAD

**Issue by egnimos** [superlistapp/super_editor#1048]
I'am using 

Flutter Version: 3.7.3
and the latest code of super_editor from the main branch

every time I click on the toolbar to edit the selected text, the **selection** properties of the given **DocumentComposer** object becomes null

as you can see in the video:

https://user-images.githubusercontent.com/54541657/222393918-2b0dff84-eef1-4b78-b4b9-bde48de8c09a.mp4

how can I resolve this
please help me 
thanku :)

**Comment by matthew-carroll** [comment]
@egnimos it looks like your toolbar is taking focus when you tap the dropdown box. When `SuperEditor` loses focus, by default, it hides the selection. It then looks like the dropdown is immediately closing, and giving focus back to `SuperEditor`, which then restores the selection.

The Super Editor example app also has a problem with the drop down list because the drop down list steals focus from `SuperEditor` without providing any way to prevent that from happening. Unfortunately, if you want to use a dropdown list, you will probably have to build your own drop down list, so that your dropdown list can share focus with `SuperEditor`.

Please let me know if that's sufficient information to close this ticket.

**Comment by matthew-carroll** [comment]
I'm going to close this ticket for inactivity.
