### ISSUE TITLE
[SuperEditor] Support for non-deletable document nodes

### ISSUE THREAD

**Issue by kpsroka** [superlistapp/super_editor#1066]
I'm implementing a feature where some components in the editor are being visually hidden, while still being present in document's node list, so that the underlying structure gets preserved for serialization without creating some kind of mapping between visual and logical structure. Such components should be ignored during visual editing, as if they are not there, ie. they are not being copied, moved, deleted, or affected by text attribution change.

While I can have SuperEditor ignore the nodes/components for copying and change by having a custom facade component that reports empty text, displays nothing, and can't be selected, I cannot change SuperEditor's behavior wrt deletion. I tried to work around it by reversing effects of deletion operation, I think that it's not very productive, as it tries to deduct what happened, and restore the state from before deletion, leading to complicated logic that is hard to get right (esp. since some editor operations have side effects apart from node deletion, e.g. selection change).

I'd like to have a capability in SuperEditor to have some nodes protected from removal from document, and skipped in context of deletion, so that operations that would affect them are either ignored or passed on to a (deletable) node before or after them as appropriate.

**Comment by Dboy233** [comment]
I've done this before, just add a property to the metadata. Then write a keyboardActions that checks to see if metadata is present when you delete

**Comment by matthew-carroll** [comment]
@kpsroka can you provide a minimal app that shows your best attempt to use the edit pipeline to reverse such deletions?

> I'd like to have a capability in SuperEditor to have some nodes protected from removal from document, and skipped in context of deletion...

I'm skeptical that this is something we should add. One can imagine any number of such exceptions. Instead, if a change is going to be made at all, we need to find a reasonable place to add control, so that a developer might make any such decision. But I think that looking for such a place first requires that we better understand the difficulty of using request/command overrides, and using reactions to accomplish your goal.

**Comment by matthew-carroll** [comment]
Thanks for following up. I'm going to close this ticket.
