### ISSUE TITLE
Fill the empty spaces while dragging the selection in the same paragraph

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#115]
When we drag and select words, characters in the paragraph, it shows empty lines between the selected paragraph elements. But for the same paragraph, it should not show the empty space.

Current:
![Screen Shot 2021-04-13 at 12 44 09](https://user-images.githubusercontent.com/24432752/114532877-f286b600-9c55-11eb-81a5-0b89f610c855.png)

Reference (Medium):

![Screen Shot 2021-04-13 at 12 43 46](https://user-images.githubusercontent.com/24432752/114532827-e69af400-9c55-11eb-96d1-3830c9c32f27.png)

**Comment by matthew-carroll** [comment]
The selection boxes are calculated by Flutter's underlying text layout system. I'm not sure what the best solution for this issue is at this time.

We could add some pixels to the height, but then what happens when the text is made larger or smaller?

Maybe the height needs to be multiplied by the `TextStyle` `height` property.

Some investigation is required.
