### ISSUE TITLE
Setting background-color in custom ComponentBuilder prevents editing

### ISSUE THREAD

**Issue by proformance** [superlistapp/super_editor#1150]
Hi,

Great job with super_editor!

I was playing around with the example code for **AnimatedTaskComponentBuilder**. After making the following minimal change I can select the text **only** when the color is set to _null_.

**So the problem is that the text is no longer selectable if it has color set to anything else than null**

<img width="1242" alt="Screenshot 2023-05-24 at 07 27 33" src="https://github.com/superlistapp/super_editor/assets/18383533/361e5a5e-d018-4cfa-8f3f-8ac395259a90">

(If I wrap everything with an IgnorePointer it works again, but that workaround prevents me from e.g. showing an icon only when hovering that component.)

https://github.com/superlistapp/super_editor/assets/18383533/59af4d25-06a8-4c77-ba51-eb94fa895665

Here is an example, branched out from the stable-branch: https://github.com/proformance/super_editor/tree/background-color-problem

**Comment by proformance** [comment]
Thanks for your comment, I tried to clarify the issue

**Comment by angelosilvestre** [comment]
@matthew-carroll The issue seems to be that when using the color property, the `Container` adds a `ColoredBox` in the widget tree. The `ColoredBox` has an `opaque` hit test behavior, and it seems to be preventing the document layout to receive the gestures: 

```dart
class _RenderColoredBox extends RenderProxyBoxWithHitTestBehavior {
  _RenderColoredBox({required Color color})
      : _color = color,
        super(behavior: HitTestBehavior.opaque);
```

It's possible to use a custom implementation of a `ColoredBox` which would use `HitTestBehavior.translucent`. That way the selection would work as expected.

I'm not sure if there's anything we could do on our side.

**Comment by matthew-carroll** [comment]
I'm going to close this due to inactivity. If the issue persists, please check the above questions/recommendations. If they don't help, please file an updated ticket.
