### ISSUE TITLE
Performance regressions

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#1236]
I was recently profiling energy usage and have noticed that there are some significant performance regressions in super_editor.

A while ago https://github.com/superlistapp/super_editor/pull/285 got merged to fix blinking cursor performance, but later it was replaced by [BlinkController](https://github.com/superlistapp/super_editor/blob/main/super_text_layout/lib/src/infrastructure/blink_controller.dart), which uses a `Ticker`. Unlike custom timer `Ticker` on desktop runs at constant 60 fps (each tick requesting new frame), causing unnecessary repaints given that cursor blinking interval is much longer.

This is further exacerbated by the fact that super editor forces repaint even if cursor is not visible. This is caused by [DocumentCaretOverlay](https://github.com/superlistapp/super_editor/blob/c6e2cfe5a0f0f0a097ab30707d6e337502cbc8b8/super_editor/lib/src/default_editor/document_caret_overlay.dart#L37) calling `startBlinking` on `BlinkController` unconditionally in `initState`. Regardless of whether there is any selection or whether the editor is focused).

Initially I assumed that removing `startBlinking` from `initState` would fix this, but that's not the case because `DocumentCaretOverlay` state gets torn down and re-inflated every time content layer gets rebuilt (i.e. on selection change). Which seems like a strange behavior caused by [ContentLayers](https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/infrastructure/content_layers.dart). Every time layers are rebuilt, the child elements are [inflated](https://github.com/superlistapp/super_editor/blob/c6e2cfe5a0f0f0a097ab30707d6e337502cbc8b8/super_editor/lib/src/infrastructure/content_layers.dart#L146), which throws away the previous element state recreating the element tree from scratch. This seems at odds with how rest of Flutter works, where instead of always calling `inflate`, the element would normally call [updateChild](https://github.com/flutter/flutter/blob/b2e22d3558e8334d4427ed9b78d21a347375fad2/packages/flutter/lib/src/widgets/framework.dart#L3649) which allows preserving state of elements in tree if widgets are compatible.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@knopp would you be interested in pairing on this? The `ContentLayers` stuff is pretty hairy. It's definitely trying to do stuff that Flutter doesn't want to do, but that's because, in my opinion, Flutter is missing some important capabilities around build invalidation.

Here's an issue I filed with Flutter: https://github.com/flutter/flutter/issues/123305

I've found it pretty difficult to track what I'm supposed to do from an `Element` and `RenderObject` perspective when implementing non-trivial multi-child behavior. Maybe you can help me find places for improvements in `ContentLayers`?

**Comment by matthew-carroll** [comment]
Also @knopp part of this rebuild behavior is probably on purpose. The `Element` getting recreated might not be intentional, but rebuilding the layers whenever the content changes is intentional. The purpose of the content layers is to size and position widgets based on the content layout. For example, a caret positioned within some text. If the text layout changes, then the caret position should also change, which requires a rebuild of the caret widget.

**Comment by matthew-carroll** [comment]
I tried an adjustment here: https://github.com/superlistapp/super_editor/pull/1239

I added a test that expects the overlay and underlay `Element` to remain the same across a rebuild.

Unfortunately, a few caret position tests broke.
