### ISSUE TITLE
[Web] Japenese & Emoji IME popovers in wrong position

### ISSUE THREAD

**Issue by brian-superlist** [superlistapp/super_editor#1356]
**Reproduction**

  1. Launch Super Editor Example on super_editor main branch / flutter master branch as a MacOS Desktop App
  3. Run main demo or super text field demo
  4. On MacOS, Open emoji popover. Popover appears in correct position
  5. On MacOS, enable Japanese Romanji Keyboard.
  6. From the Keyboard Selection menu, choose "Hiragana - Romanji"
  7. Type the letters "sa"
  8. Japanese IME popver should appear in correct position
  9. Launch example app as a Chrome Web App
  10. Repeat Steps 4-8.
  11. Emoji & Japanese IME popovers appear in the wrong part of the screen.

**macOS (working)**

https://github.com/superlistapp/super_editor/assets/90610075/4fbf6ea0-477e-47ca-ae2d-6e3228bf9ad4

**Chrome (not working)**

https://github.com/superlistapp/super_editor/assets/90610075/b1cfcef6-ea80-4cd6-8cff-bc8618c5789f

**Comment by matthew-carroll** [comment]
@brian-superlist can you confirm that a regular Flutter text field in that web situation works as expected?

**Comment by brian-superlist** [comment]
I just tested the regular Flutter Text Field. The japanese & emoji IMEs are displayed in the correct location.

**Comment by angelosilvestre** [comment]
@matthew-carroll @brian-superlist  This seems to be a Flutter web limitation. Even Flutter `TextField` isn't 100% accurate with the position:

https://github.com/superlistapp/super_editor/assets/7597082/2e6fc5e0-2d71-4f77-858e-b3d510d40b25

Looking into the engine code, it seems that `setCaretRect`, which effectively sets where the panel should be displayed,  isn't supported on web: 

```dart
class TextInputSetCaretRect extends TextInputCommand {
  const TextInputSetCaretRect();

  @override
  void run(HybridTextEditing textEditing) {
    // No-op: not supported on this platform.
  }
}
```

I assume that, on web, the emoji picker works by setting the text into a hidden input and then the browser positions the caret rect where it thinks it should be. One thing I noticed is that `EditableText` calls `setStyle` to make the hidden input style match `EditableText`'s style. The `setStyle`docs say:


```dart
/// Send text styling information.
///
/// This information is used by the Flutter Web Engine to change the style
/// of the hidden native input's content. Hence, the content size will match
/// to the size of the editable widget's content.
```

As `EditableText` has only one style, the text position of the selected character on the hidden input can be close to the position it has on `EditableText`.

On `SuperTextField`, we can call `setStyle` with the default style to make it a bit better, but not 100% accurate.

Without `setStyle`:  

https://github.com/superlistapp/super_editor/assets/7597082/0c3f8008-4408-4080-bbf6-20a0cdd5c317

With `setStyle`: 

https://github.com/superlistapp/super_editor/assets/7597082/afdbe80d-68ec-4ef6-a6b6-9deb36b3bed1


In `SuperEditor`, I think the best we can do is to call `setEditableSizeAndTransform` with size and transform of the selected node's visual component instead of the editor size and transform, as we are currently doing.

Maybe we should file a Flutter issue to confirm if there isn't really a way to set the caret rect on web.

**Comment by matthew-carroll** [comment]
I spoke with Angelo. He's going to try reporting editor bounds on a per component basis to the IME.

**Comment by angelosilvestre** [comment]
Filed https://github.com/flutter/flutter/issues/134265 and https://github.com/flutter/flutter/issues/134268 to see what the Flutter team has to say about these issues.

Opened https://github.com/superlistapp/super_editor/pull/1418 with the proposed changes.
