### ISSUE TITLE
Checkboxes can't be indented nor created with "- [ ]"

### ISSUE THREAD

**Issue by NicoEssi** [superlistapp/super_editor#1365]
Identified three issues with the checkboxes.

1. Creating checkboxes similar to other markdown editors (e.g. GitHub, Obsidian, et cetera) with "- [ ]" does not work. If there is another way to create these checkboxes without the toolbar; I am unable to find it documented anywhere. Clashes with markdown UX expectations.
2. Unable to indent checkboxes with tab. When hovering over a checkbox line, tabbing seems to just change focus. Clashes with markdown UX expectations.
3. Pressing enter on an empty checkbox does not make it disappear, as is standard for markdown editors. Clashes with markdown UX expectations.

Reproduction recorded: 
![Screen Recording 2023-09-01 at 09 31 40](https://github.com/superlistapp/super_editor/assets/31189442/fc351d00-c1cc-4012-bcac-d5b03d9eef89)

**Comment by matthew-carroll** [comment]
Please track this PR for Markdown support: https://github.com/superlistapp/super_editor/pull/1360

For the other two issues, can you please file separate tickets so that we can address individually? You can edit this ticket to become one of those two tickets.

When describing expectations, please be precise about what's happening now vs what exactly you think should happen.

**Comment by matthew-carroll** [comment]
I'm going to close this ticket due to inactivity. If you have specific, individual issues that you'd like for us to address, please file one ticket per issue, and please fully describe the actual vs desired behavior.
