### ISSUE TITLE
[SuperTextField] ESCAPE key event is not bubbling up

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1408]
Steps to reproduce:
* Wrap a `SuperTextField` with `Actions` widget that handles the `DismissIntent` (usually invoked when ESCAPE is pressed)
* Give focus to the field
* Press ESCAPE

**Expected:** the handler in `Actions` for the `DismissIntent` is invoked
**Actual:** nothing happens

Here's a code snippet with the changes that I made in the build method of `InteractiveTextFieldDemo`:
<details>
  <summary>Code snippet</summary>

  ### Before
  ```dart
  @override
  Widget build(BuildContext context) {
    return TapRegion(
  ```
  ### After
  ```dart
  @override
  Widget build(BuildContext context) {
    return Actions(
      actions: {
        DismissIntent: CallbackAction<DismissIntent>(
          onInvoke: (_) {
            print('DismissIntent');
            _focusNode!.unfocus();
            return () {};
          },
        ),
      },
      child: TapRegion(
  ```
</details>

From trying different commits, it seems that this was introduced in 3df65bf8d311ceb8c914b676bd37a1a7bf212cfb.

The ticket mentions explicitly the ESCAPE key, but this could be applicable for other keys, although I haven't come across other issues.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by angelosilvestre** [comment]
@matthew-carroll Is this related to the changes to the key handlers we discussed recently?

**Comment by matthew-carroll** [comment]
@miguelcmedeiros is this Mac desktop or Mac web?

**Comment by matthew-carroll** [comment]
@angelosilvestre if you mean what we discussed yesterday, I haven't merged those changes yet, and I think that will only impact `SuperEditor` and not `SuperTextField`.

**Comment by miguelcmedeiros** [comment]
> is this Mac desktop or Mac web?

@matthew-carroll it is mac desktop

**Comment by angelosilvestre** [comment]
@matthew-carroll @miguelcmedeiros This issue is caused because now `SuperTextField` handles `DoNothingAndStopPropagationTextIntent` to prevent arrow keys from performing focus traversal.

 `WidgetsApp` places a `DefaultTextEditingShortcuts` in the widget tree, which is mapping the escape key to `DoNothingAndStopPropagationTextIntent`. As a result, `SuperTextField` is handling this intent and preventing the escape key from bubbling up.

One solution is to place a `Shortcuts` widget bellow `MaterialApp` (or `WidgetsApp`) to re-map the escape key: 

```dart
 Shortcuts(
    shortcuts: <ShortcutActivator, Intent>{
      const SingleActivator(LogicalKeyboardKey.escape): DismissIntent(),
    },
   child: ...
);
``` 

This way, the desired intent will reach the `Actions` widget.

Or we can try to `DoNothingAndStopPropagationTextIntent` and see if there are other intents that could work for us.

**Comment by matthew-carroll** [comment]
@angelosilvestre @miguelcmedeiros are there any other keys that would be relevant for this issue? Are there any other non-content keys that the user is supposed to be able to press? Or is it truly just arrow keys and escape?

**Comment by miguelcmedeiros** [comment]
I can think of Home/End keys to move the selection to the start/end of the content.

**Comment by matthew-carroll** [comment]
I guess page up/down is also in that list.

@angelosilvestre can you check if there's a more specific set of ignore intents?
