### ISSUE TITLE
[SuperEditor] - Links don't show click cursor in command mode

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1441]
In `SuperEditor` a user can press CMD to enter command mode and tap a link to open the associated webpage.

The link clicking behavior works, but the cursor no longer dependably displays the click cursor. It shows for some moments and then disappears. It seems to be conflicting with some other signal.

Get the click cursor working again.

I've also noticed that when the cursor is over the document, it no longer looks like a text cursor, it looks like a regular cursor. When over the document, the cursor should look like a text cursor. It seems like something has changed that's impacting cursor settings throughout the editor.

**Comment by rutvik110** [comment]
> I've also noticed that when the cursor is over the document, it no longer looks like a text cursor, it looks like a regular cursor. When over the document, the cursor should look like a text cursor. It seems like something has changed that's impacting cursor settings throughout the editor.

I'm able to reproduce this on main after pulling the latest updates. Seems like this was introduced from an update within last week. I'll check into what caused it and have it fixed.

**Comment by rutvik110** [comment]
So currently on main, when the document has focus, pressing CMD and hovering over a `SuperEditor` link is showing the click cursor as expected,

https://github.com/superlistapp/super_editor/assets/65209850/53e79f08-39a7-4293-8fcd-0bc711c0e89c

The actual issue seems to be when when the document doesn't already have the focus and we perform this action. In that case, key events are not recorded so the interactive mode is never on and thus we still show the text cursor.

https://github.com/superlistapp/super_editor/assets/65209850/c1e5e17a-170d-459b-b277-85a6907f0ee9

Requesting focus manually within `initState` when we load the document resolves this,
```dart
    if (widget.autofocus) {
      onNextFrame((timeStamp) {
        _focusNode.requestFocus();
      });
    }
```
 Demo with above changes added: 

https://github.com/superlistapp/super_editor/assets/65209850/4e03106d-b0e3-4efb-b88d-720eab101b43


So, should we manually request focus when we first load the doc if auto-focus is enabled by the user?

**Comment by matthew-carroll** [comment]
> So, should we manually request focus when we first load the doc if auto-focus is enabled by the user? Is that the behaviour we would want?

No. The behavior you're demonstrating is the correct behavior. Are your demos run on Mac? Also, did you check on web?

**Comment by rutvik110** [comment]
yes, the demo's running on mac. I'll confirm this behaviour on web once.

**Comment by rutvik110** [comment]
On web, I can see this issue. And it's seems to not only limited to interactive mode on a link but also other interactive widgets like `CheckBox` within document.

https://github.com/superlistapp/super_editor/assets/65209850/fa176c35-34ca-49f1-8146-f034cee8fcc1

**Comment by rutvik110** [comment]
> On web, I can see this issue. And it's seems to not only limited to interactive mode on a link but also other interactive widgets like `CheckBox` within document.
> 
>  Screen.Recording.2023-09-21.at.6.00.04.PM.mov

This doesn't seem to be an issue any longer on the web on main. 

https://github.com/superlistapp/super_editor/assets/65209850/124f4c95-c068-4ae3-a2bd-b3a24dc3e55f

Some update along last week seems to have fixed this but I'm not sure which update it was. Will check into that and I'll probably write a few tests to lock down this behaviour. 
Beside that, I don't happen to encounter any problems now across web and desktop that are described in this issue.

**Comment by matthew-carroll** [comment]
Closing as can't reproduce.
