### ISSUE TITLE
Magnifying & Toolbar Positioning is Incorrect on Scroll Change

### ISSUE THREAD

**Issue by brian-superlist** [superlistapp/super_editor#1548]
In the Superlist app, when a user starts editing the document and the keyboard opens, we scroll the selected content so it appears in the middle of the available space. When this happens, the mangifier and toolbar positions are not updated correctly.

When the scroll position of the document changes, the toolbar & magnifier positions should be updated accordingly.

Reproduction:

  1. Double tap to start editing
  2. Scroll the content into place
  3. Toolbar is displayed incorrectly
  4. Same thing happens for magnification

https://github.com/superlistapp/super_editor/assets/90610075/fd672bb7-ea04-4c18-97a8-f39d6626030a

https://github.com/superlistapp/super_editor/assets/90610075/55b6c780-2976-4801-bae3-4196b8a44bf4

**Comment by matthew-carroll** [comment]
@brian-superlist @miguelcmedeiros are you able to repro these issues in the latest version of the Example app?

**Comment by miguelcmedeiros** [comment]
I was testing against the latest commit in `main` (this issue was opened running Superlist against `24aef3e03a35b6c38963e1ece80b3b57eeb1c358`), both the demo app and Superlist, and I could reproduce the issue with the toolbar anymore.

I also couldn't reproduce the same issue with the magnifier, but there are other issues related to long pressing. Those might fall under https://github.com/superlistapp/super_editor/issues/1547.

@brian-superlist could be retest this against the latest commit?

**Comment by brian-superlist** [comment]
Closing this one for now as I'm also unable to reproduce on latest version of main.
