### ISSUE TITLE
Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'

### ISSUE THREAD

**Issue by hillelcoren** [superlistapp/super_editor#155]
As referenced in #1 I'm seeing the following error when trying to test out the package:

```
$ flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../lib/src/default_editor/document_interaction.dart:639:31: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.

 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../../../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').

      onKey: (node, event) => true,

                              ^
Waiting for connection from debug service on Chrome...             13.5s
Failed to compile application.
```

I can reproduce the error with the sample project using Chrome and Windows, here's my Flutter info.

```
$ flutter --version
Flutter 2.3.0-0.1.pre • channel dev • git@github.com:flutter/flutter.git
Framework • revision d72bfb8d07 (10 days ago) • 2021-04-26 06:05:55 -0700
Engine • revision de6e1adf97
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

**Comment by venkatd** [comment]
I think this is because the most recent API may have changed:

https://github.com/flutter/flutter/blob/b8a2456737c9645e5f3d7210fba6267f7408486f/packages/flutter/lib/src/widgets/focus_manager.dart#L58

It now is meant to return a `KeyEventResult` for later versions of Flutter:

This looks to be the commit where the change was made:
https://github.com/flutter/flutter/commit/36daea2d54a171591b7c96f383d7bc028d918f8f#diff-74c1ea0c32ab7297d9ad3ac6ce82dc556b8ba64b8feeb78bcaa38b623aaeb747L59

**Comment by matthew-carroll** [comment]
@hillelcoren can you try this again with v0.1.0? I think I may have fixed this in the course of other work.

**Comment by creativecreatorormaybenot** [comment]
Some context on the API change: it actually used to take both types for a while, for backwards-compatibility, but the `KeyEventResult` return type is more descriptive anyway IMO.
