### ISSUE TITLE
Update iOS magnifier design and functionality for iOS 17

### ISSUE THREAD

**Issue by Jethro87** [superlistapp/super_editor#1551]
The design and functionality of the iOS magnifier seem to have changed in iOS 17. Specifically:
- The magnifier is much bigger
- There's a new animation when it first appears
- When moved quickly (while still pressing), the magnifier disappears and the carat can be placed.

https://github.com/superlistapp/super_editor/assets/6467808/0db2c302-51b5-4338-afc2-5ce3a0fadc9d

Possibly related to #1550 and https://github.com/Flutter-Bounty-Hunters/swift_ui

**Comment by Jethro87** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@Jethro87 this ticket will probably take a bit longer to get to than some other recent tickets, because this is more of an enhancement than a bug fix.

What we're definitely going to need to match this is a clear specification. Anything you can do to provide that will save us time when we get to it. 

For example, what exactly is the policy for hiding the magnifier? After it hides does it ever come back?

What's the policy for the magnifier not exactly following the finger?

Etc.

We'll have to figure out those details one way or another.

**Comment by matthew-carroll** [comment]
Update: I believe as of now we have the desired size, shape, and intro animation for the magnifier. We still lack the heuristic to make the magnifier disappear while dragging.

@Jethro87 can you tell what that heuristic is? Does the magnifier disappear as soon as you drag down a line? Or is there something more to it?

**Comment by matthew-carroll** [comment]
I'm going to close this due to lack of actionable info about further magnifier adjustments. The magnifier jumping heuristic is captured in a different ticket: https://github.com/superlistapp/super_editor/issues/1605

**Comment by BazinC** [comment]
> I'm going to close this due to lack of actionable info about further magnifier adjustments. The magnifier jumping heuristic is captured in a different ticket: #1605

The ticket you mention is related to Android. I think this recently closed ticket regarding iOS Magnifier makes more sense https://github.com/superlistapp/super_editor/issues/1958
