### ISSUE TITLE
[question] What is the best way to depend on the super_editor package?

### ISSUE THREAD

**Issue by jellynoone** [superlistapp/super_editor#1618]
There seems to be two ways to depend on the package:
- using a git branch directly or
- depending on the version published on pub.dev

However, the pub.dev version seems to be quite old (relative to the amount of updates that happened since then), in addition there seems to have been frequent publications to pub.dev back in May. So, I wonder if there has any change in the expected way a user would depend on the package or if some internal policy about publications to pub changed.

So my question is what way is it expected that the package is dependent on via pub.dev or git? If the latter, could a note be put in the Readme so that this information can be more easily discovered?

And out of curiosity, why has publications to pub stop? At least how I understand it, pub has a promise to never let the package / source be removed. While depending on git directly, could in theory, one day become outdated if the package shuts down (hopefully not) and the github repository removed.

**Comment by matthew-carroll** [comment]
At the moment, developers should rely on the GitHub version. We're in the middle of a number of major changes (atomic commands, reactions, undo/redo), which is why the GitHub version is so out of date with the Pub version. This isn't a permanent state of affairs, it's specific to the problems we're currently solving. After the next major release, Pub will probably be much more up to date with the GitHub version.

I'm going to close this issue because there's no particular action item that I can see.

**Comment by jellynoone** [comment]
Thank you for letting me know. Makes sense.

Perhaps this information could be added to the Readme or this issue be pinned so this information can be more easily discovered. I think some reported issues like the ones for outdated dependencies might not have been reported had the users known they should have been using the GitHub version.
