### ISSUE TITLE
[Web/macOS] [SuperEditor] First character in paragraph is not part of composing region when using Japanese-Romaji

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#1641]
Setup:
* macOS 13.4.1
* Browser: Chrome 119.0.6045.199
* Keyboard: Japanese-romaji

Steps to reproduce:
* Run the demo app on a browser
* In a `SuperEditor` demo, add a new paragraph
* Place the caret in the empty paragraph and type "kamera"

Expected: "カメラ"
Actual: ”kあめら”

Notes:
* Could not reproduce this issue when running on macOS native
* Could not reproduce this issue on Windows, but found a different one (filled a separate ticket)
* Could not reproduce this issue with `SuperTextField`

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll

**Comment by angelosilvestre** [comment]
@matthew-carroll This seems to be caused by the same issue of https://github.com/superlistapp/super_editor/issues/1642

The empty paragraph has the placeholder text `. `. When we type the first character in the paragraph, we remove this placeholder and send the resulting value back to the IME.

It seems that, at least on web, if we change the editing state while the IME is composing, the IME gets confused.

I added some logs to the web engine with resulted in: 

Pressing "k" on an empty paragraph:

```console
composition started
composition updated with text "k"
New event received: "beforeinput"
Event data: "k"
Input type: "insertCompositionText"
New event received: "input"
Event data: "k"
Input type: "insertCompositionText"
Dom element value: ". k"
Editing state after change: EditingState(". k", base:3, extent:3, composingBase:2, composingExtent:3)
Received new editing state from the framework: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
New dom element value: "k"
New event received: "selectionchange"
Event data: "null"
Input type: "null"
Dom element value: "k"
Editing state after change: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
New event received: "selectionchange"
Event data: "null"
Input type: "null"
Dom element value: "k"
Editing state after change: EditingState("k", base:1, extent:1, composingBase:0, composingExtent:1)
```

Pressing "a" on the same paragraph:

```console
composition started
composition updated with text "あ"
New event received: "beforeinput"
Event data: "あ"
Input type: "insertCompositionText"
New event received: "input"
Event data: "あ"
Input type: "insertCompositionText"
Dom element value: "k あ"
Editing state after change: EditingState("k あ", base:2, extent:2, composingBase:1, composingExtent:2)
New event received: "selectionchange"
Event data: "null"
Input type: "null"
Dom element value: "k あ"
Editing state after change: EditingState("k あ", base:2, extent:2, composingBase:1, composingExtent:2)
```

We can see that, after pressing "a", composition started again.

When the engine receives a new editing value, it sets the value and selection to the dom element, so I'm assuming there is no API to change the composing region of the input element.

If we always prepend the editing value with the ". ", then the issue doesn't happen. Do you know if this could cause any problems?

**Comment by matthew-carroll** [comment]
It looks like retaining the ". " would solve this issue and another issue. I thought that I already made that change a while ago. Maybe I discovered a reason that we couldn't keep it? I'd say go ahead and try to make that change and let's see if we can keep everything working.
