### ISSUE TITLE
[SuperEditor] Does MutableDocument intentionally allow nodes to be modified outside of the document?

### ISSUE THREAD

**Issue by jellynoone** [superlistapp/super_editor#1696]
When working on #1648, I noticed that currently `MutableDocument` allows for nodes to be modified outside of the methods provided by the document.

Currently, `MutableDocument` is defined as:
https://github.com/superlistapp/super_editor/blob/fa9ad4483f46b6091a108e7f00e764a187a21530/super_editor/lib/src/core/editor.dart#L493-L497

However, this setup allows for the caller to modify nodes from outside the document if they keep a reference to the nodes.
For instance, doing:
```dart
  final nodes = <DocumentNode>[];
  final document = MutableDocument(nodes: nodes);

  nodes.insert(0, TextNode(id: '<id>', text: AttributedText()));

  print(document.nodes); // prints [[TextNode]...]
  print(document.getNodeById('<id>')); // prints null
```

Is this behaviour expected or is the intent that the nodes always stay private and that the constructor should behave as:
```dart
  MutableDocument({
    List<DocumentNode>? nodes,
  }) : _nodes = [...?nodes] {}
```

**Comment by matthew-carroll** [comment]
All changes to the `MutableDocument` should be done through `Editor` commands. The `MutableDocument` API is largely due to the fact that we didn't used to have requests and commands, but now we do. 

I don't know if we'll ever completely hide `MutableDocument` because anyone can provide any object they want as an editable inside the `Editor`. Instead, users should recognize that any objects they put inside an `Editor` as an `Editable` shouldn't be mutated outside of commands.
