### ISSUE TITLE
[SuperEditor][Example][Desktop] - Caret doesn't display on trailing edge of header image

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#1709]
In `SuperEditor` you're supposed to be able to place the caret on the leading and trailing edges of an image (or any other block component). 

Currently, when tapping near the leading edge of the header image in the example app, the caret correctly appears on the leading edge. However, when tapping near the trailing edge, no caret is visible at all.

Fix this by making the caret visible on both sides of an image.

**Comment by angelosilvestre** [comment]
@matthew-carroll  The issue seems to be that we are placing the caret out of bounds.

This is the method that computes the caret rect for box components:

```dart
@override
Rect getRectForPosition(dynamic nodePosition) {
  if (nodePosition is! UpstreamDownstreamNodePosition) {
    throw Exception('Expected nodePosition of type UpstreamDownstreamNodePosition but received: $nodePosition');
  }

  final myBox = context.findRenderObject() as RenderBox;

  if (nodePosition.affinity == TextAffinity.upstream) {
    // Vertical line to the left of the component.
    return Rect.fromLTWH(-1, 0, 1, myBox.size.height);
  } else {
    // Vertical line to the right of the component.
    return Rect.fromLTWH(myBox.size.width, 0, 1, myBox.size.height);
  }
}
```

We are placing the caret outside the component's bounds. We can see that, for upstream selections, we are partially clipping the caret (the caret is configured to 2px):

![Captura de Tela 2024-01-02 às 11 37 19](https://github.com/superlistapp/super_editor/assets/7597082/8b647cf5-d961-4012-8311-5fb6bbbda625)

If we change the `getRectForPosition` to set the rect left to zero instead of -1, we can see that the caret appears thicker:

![Captura de Tela 2024-01-02 às 11 38 18](https://github.com/superlistapp/super_editor/assets/7597082/389cc7af-a8ff-4f23-8e59-bba4a6a2302d)

If we change the `getRectForPosition` to set the rect left `width -1` for downstream selections, we can see that the caret is displayed:

![Captura de Tela 2024-01-02 às 11 42 21](https://github.com/superlistapp/super_editor/assets/7597082/3a2edb36-a85b-4e71-86ee-ce3de1363b37)

The horizontal rule component correctly displays the downstream caret because it doesn't take all the space.

![Captura de Tela 2024-01-02 às 11 21 26](https://github.com/superlistapp/super_editor/assets/7597082/40e3b724-be1b-4a4d-908c-5a834754aca7)

While the image component do take all space:

![Captura de Tela 2024-01-02 às 11 21 53](https://github.com/superlistapp/super_editor/assets/7597082/91083583-53f1-4821-a7e8-0bafa41ca7c6)

Should we position the caret totally inside the box component bounds, taking into consideration the caret's width?

**Comment by matthew-carroll** [comment]
You mentioned that the image in clipping the caret, but isn't the caret layer on top of the components in the document layout? I don't think components should be able to clip or hide the caret at all, can they?

**Comment by angelosilvestre** [comment]
I mean something like the document layout. But even without the clipping, if the image is taking the whole width and we are positioning the caret to the right of the widget, the caret ends up being off-screen.

**Comment by matthew-carroll** [comment]
> But even without the clipping, if the image is taking the whole width and we are positioning the caret to the right of the widget

That makes sense, but I'm still unclear about the clipping. What's clipping what?

**Comment by angelosilvestre** [comment]
I'll take a deeper look to see if I can find out where this is happening.

**Comment by angelosilvestre** [comment]
@matthew-carroll `CaretDocumentOverlay` is clipping the caret. It uses a `Stack` without a `clipBehavior` set, so it defaults to `Clip.hardEdge`.

**Comment by matthew-carroll** [comment]
Ok, let's remove that clipping. I can't think of any reason that we'd need or want clipping.

**Comment by angelosilvestre** [comment]
Ok, but even removing the clipping, we still need to make some change on where the caret is positioned for block components.

After https://github.com/superlistapp/super_editor/pull/1744, the upstream caret is positioned at (0,0) and the downstream caret is positioned at (right, 0), so when the image takes all the available screen width (like in the demo app), the caret is positioned off-screen.

Maybe we could do some change in `CaretDocumentOverlay` to change the positioning when we have a downstream selection on a box component.

Do you have other ideas?
