### ISSUE TITLE
[SuperTextField] [Bug] Drawing caret problem on two or more Text Fields and focus change. 

### ISSUE THREAD

**Issue by salihgueler** [superlistapp/super_editor#173]
Steps to reproduce.

- Checkout repro_text_field_focus_problem branch
- Run the example application
- Click on SuperTextField from the sidebar
- Click on the "Single-line demo" from right side
- Click on the first Text Field
- Click the "Focus to second field" button
Expected:
- It should focus on the second field and draw a caret
Actual:
- It has the focus and shows focus but doesn't draw a caret

**Comment by venkatd** [comment]
I haven't tried the example itself, but if it helps, our app uses multiple instances of SuperTextField and we haven't had issues with carets rendering.

One possible related issue: I needed to pass in an AttributedTextEditingController with a valid `selection` property because it defaults to `TextSelection.collapsed(offset: -1)`. That prevented the caret from drawing because the selection wasn't in bounds.

This might not be related but sharing just in case.

**Comment by matthew-carroll** [comment]
The root cause of the reported issue is that focus is moved to a new `SuperTextField` without setting a `TextSelection`. It's behaving as intended, however, that intended behavior might not be ideal.

I recreated the focus shift with regular `TextField`s in Dart Pad. That behavior shows that whenever a `TextField`'s `FocusNode` request's focus, the `TextField` automatically places the `TextPosition` at the end of any entered text. I'll make `SuperTextField` do the same thing until we hear of any reason to do otherwise.
