### ISSUE TITLE
Show the current block (node) with markdown markup and render the rest

### ISSUE THREAD

**Issue by thomastthai** [superlistapp/super_editor#1748]
**Package Version**
super_editor, GitHub, stable branch

I finally got `super_editor` demo running. It looks very capable!

What I'm looking to do is be able to load a markdown document. The whole document gets rendered in the "preview" mode. Then if I click on a block/node (paragraph, ordered list, etc.), only that block/node would be shown in markdown markup so edits can be done using markdown syntax while the rest of the blocks render in preview mode. Then if I click away from that block that I was editing, it would get rendered.

Or if an empty document was started, the document would be in markdown syntax mode. I start typing header and press enter to complete that block/node. It gets rendered as a header. In the next line which starts the next block/node, that block/node is now in markdown syntax mode. Once that block/node is completed, it gets rendered in "preview" mode.

How could that be accomplished?

**Comment by matthew-carroll** [comment]
This is something that I've tentatively planned to implement outside of `SuperEditor` for a while, but I haven't gotten around to it yet.

That behavior will require some significant configuration of `SuperEditor`, but here's the starting point:

A `ParagraphNode` holds the logical content for a paragraph. A `TextComponent` decides how to paint a paragraph within the document. A `ParagraphNode` is connected to a `TextComponent` through a `ParagraphComponentBuilder`.

What you probably want to do is provide your own extension of `TextComponent`, or perhaps you should introduce an entirely new component like a `MarkdownTextBlockComponent`. Within that component's widget tree, when the user places the caret in the component, or selects content within the component, then you would display the Markdown characters like `##`, `**`, etc. When the user's selection leaves that component, such as tapping to place the caret in a different area of the document, then you rebuild the component's widget tree and remove the Markdown syntax.

If you're new to `SuperEditor` this probably sounds like a lot to figure out. I would recommend trying to make one tiny change after another to get there. You should also make use of the Example app to see various ways that `SuperEditor` can be configured.

I'm going to close this issue because it's not actionable. If you'd like to engage in conversations about `SuperEditor`, please use the Discord channel. There aren't many people over there right now, but we're trying to move conversations to that platform instead.

**Comment by matthew-carroll** [comment]
FYI - In case the Discord link has disappeared in other places, you can access it here: https://discord.gg/jxQmPsKf
