### ISSUE TITLE
Updating single document node rebuilds entire document

### ISSUE THREAD

**Issue by knopp** [superlistapp/super_editor#1780]
Branch with example: https://github.com/superlistapp/super_editor/compare/main...knopp:super_editor:single_node_rebuilds_document

https://github.com/superlistapp/super_editor/assets/96958/49d8ebc0-c012-4b27-b1a4-534a38a92a57

cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@angelosilvestre for this ticket can you create a new example app called `example_perf` and configure it with a drawer that's similar to the existing example app? I'd like to move perf to it's own app so that we don't fill the shiny example app with ugly performance edge cases. I'm sure we'll add more over time.

Then, can you please add the given example to that app? This example currently demonstrates that rebuilding a single component in a document causes all other components to rebuild, too. But we don't want that to happen. We only want components to rebuild when they change. So the perf example we're adding is intended to show the opposite of what we're actually seeing.

With that example added, can you please see if you're able to adjust the component invalidating process so that identical component configurations don't cause rebuilds?

**Comment by knopp** [comment]
Thanks for looking into it. We had similar issue with our model.
