### ISSUE TITLE
[Super Editor] [Android] Unable to open the keyboard once I hide it with the system button.

### ISSUE THREAD

**Issue by IResetic** [superlistapp/super_editor#1816]
**Package Version**
Github stable version.

**To Reproduce**
1. Open the example app on Android device with option to hide the keybaord.
2. From the drawer menu select "Text with hint".
3. Click on the first "header goes here...".
4. After the keyboard is open press the system button to hide/close the keybaord.
5. After the keybaord is hidden, click again on the same (first one) "header goes here...".

**Actual behavior**
The keyboard stays hidden and I'm not able to enter the text. 

**Expected behavior**
I expect the keybaord to re-appear so I can add text.

**Platform**
Samsung A50 with Android 11

**Flutter version**
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4

**Comment by angelosilvestre** [comment]
@matthew-carroll The issue is that we only show the software keyboard when the selection changes. Tapping at an empty node doesn't change the selection, so the keyboard isn't shown. We had a large refactor on the IME on https://github.com/superlistapp/super_editor/pull/876, but looking at the previous code it seems this bug was present even before the PR.

We can pass the `SoftwareKeyboardController` to the mobile touch interactors. Although a user might use a physical keyboard on a mobile device, I think it's safe to assume that most of the times a mobile user will be using a software keyboard, so I think it should be ok to add a reference to `SoftwareKeyboardController` in the mobile interactors.

Any other ideas?

**Comment by hawkkiller** [comment]
@matthew-carroll @angelosilvestre we hit this bug as well.

What's the reasoning behind "showing keyboard only when selection changes"?
