### ISSUE TITLE
[BUG] - undo crash after pasting

### ISSUE THREAD

**Issue by thanhhai08sk** [superlistapp/super_editor#2173]
**Package Version**
super_editor, GitHub, stable branch

**To Reproduce**
1. Run web's example
2. Copy the last few nodes
3. Paste
4. Type in something
5. Cmd Z several times

**Platform**
Web, possibly also on Android.

**Flutter version**
3.22.2

**Screen recording**
https://github.com/user-attachments/assets/1c066631-ee90-4344-b361-437d51f14c1e

**Comment by KevinBrendel** [comment]
Can confirm this also happens on macOS.

**Comment by matthew-carroll** [comment]
I've confirmed this on Mac. I'm still trying to figure out where exactly the undo behavior is going wrong. The problem isn't always reproducible. It seems to happen the first time these steps are taken after launching the app, then things seem to work OK.

**Comment by matthew-carroll** [comment]
My working theory is that this issue is tied to the node ID of pasted content.

When content is pasted, node IDs are generated randomly. This is because we don't know how many nodes will need to be created when content is pasted, therefore we can't ask the developer/user to provide all the IDs.

This creates a hurdle for undo/redo behavior. I think the following is happening:

1. Paste some paragraphs
2. Paste inserts paragraph with ID "1234"
3. Paste inserts paragraph with ID "4321"
4. Paste inserts paragraph with ID "7890"
3. User types "a" into paragraph "7890"

Then the user runs undo. Undo completely resets the editor to a blank document, and then starts re-running the commands, which results in something like the following:

1. Paste some paragraphs
2. 2. Paste inserts paragraph with ID "6723"
3. Paste inserts paragraph with ID "9125"
4. Paste inserts paragraph with ID "5382"
3. User types "a" into paragraph "7890"

The "a" wants to insert into a node with ID "7890" (which was generated from the first paste), but after the second paste, that last paragraph has a new random ID, in this case "5382".

So it looks like I need to find a way to keep pasted IDs consistent across an undo operation.

**Comment by matthew-carroll** [comment]
@thanhhai08sk @KevinBrendel - Can you both confirm that this PR solves this issue for you? 

https://github.com/superlistapp/super_editor/pull/2190

**Comment by KevinBrendel** [comment]
@matthew-carroll Yes, it seems to solve the issue for me.

**Comment by thanhhai08sk** [comment]
Undo works, but unfortunately, I think I found another problem.

To Reproduce
Steps to reproduce the behavior:

- Run web's example
- Copy the last few nodes
- Paste
- Type in something
- Cmd Z several times
- Continue to Cmd Z even after removed all changes
- Can't type anymore

Platform
- Web

Flutter version
3.22.3

Screen recording
https://github.com/user-attachments/assets/99598b65-fb8a-489f-a60d-84d1372db00c
