### ISSUE TITLE
[SuperTextField] Unable to type quote character on international keyboards

### ISSUE THREAD

**Issue by venkatd** [superlistapp/super_editor#244]
International keyboards remap the quote key to a "Dead key" which is used to input accented characters. The quote key defaults to typing a quote if you don't go ahead and write an accent.

Steps to reproduce:
- On MacOS, go to System Preferences, Keyboard, input sources, and add U.S. International - PC, or Brazillian - Pro. Many international users use the first one so they can write in English.
- A flag will appear in the tray bar. Swap to either one of these layouts. You should see a flag in the top right next to the time as below:

![image](https://user-images.githubusercontent.com/220686/121213501-e37e4780-c843-11eb-969d-22f2e3fc8a7f.png)

- Open any SuperTextField demo in web or Mac
- Try to type a single quote or double quote
- Nothing shows up
- Expected behavior: a quote shows up

This was reported by our users as "I can't type quotes"

Ideal behavior is the dead key works to write accented characters. The short term workaround is to interpret `const _kMacDeadKey = LogicalKeyboardKey(0x100070034)` as a quote character. This wouldn't allow entering accents, but would at least allow users to type in the quote character.

**Comment by venkatd** [comment]
@matthew-carroll if we later move SuperTextField to using a deltas API, I suppose we'd be able to remove all these edge cases?

**Comment by matthew-carroll** [comment]
@venkatd given that we've invested a bit in direct keyboard input, I would recommend retaining that. We should be able to make the keyboard input configurable between direct keyboard input and IME input. That's probably a one-time cost to make that possible and then we'll always have direct keyboard input, if needed. Otherwise, if we delete it, who knows what it would require to bring it back.

**Comment by bk-one** [comment]
duplicate, closing this
