### ISSUE TITLE
Can't select empty space to start editing

### ISSUE THREAD

**Issue by UnicornsOnLSD** [superlistapp/super_editor#274]
In many cases, the editor will be in a larger text box, like this:
![image](https://user-images.githubusercontent.com/44349936/127342969-cd297522-3f7e-4f66-97a6-124bd18fbc54.png)
When the user tries to select an area in the text box, the cursor does not appear and they can't start editing. They have to actually select text currently in the box. This behaviour is also on the SuperEditor website (https://superlist.com/SuperEditor/), so this isn't just an issue with my implementation.

**Comment by britannio** [comment]
A temporary workaround if this is your only focusable widget is to listen to changes from the `DocumentComposer` and if the `selection` becomes null, set it to a non null value. Also, if you give the `SuperEditor` a `FocusNode`, you can detect when the focus node loses focus and attempt to request focus.

**Comment by matthew-carroll** [comment]
@UnicornsOnLSD can you provide the precise reproduction steps to see this on the SuperEditor website? Or can you provide the minimum code needed to reproduce the issue?

**Comment by AmitPr** [comment]
I've noticed that the cursor also doesn't change when hovering over anything that isn't text, but still contained by `SuperEditor` or `SuperTextField`. This should probably be addressed alongside this issue to make it more clear when the user's taps trigger a caret to be dropped. Probably in some sort of existing mouse-over event (I'm not exactly familiar with the details). I may try to fix this if I have time later.

**Comment by jonaird** [comment]
@matthew-carroll 
On the website click on an area within the editor that doesn't have text. This includes whitespace between blocks and also the whitespace between the last block and the bottom of the editor. The desired behavior would be to place the cursor at the last location in the closest block above.

**Comment by bk-one** [comment]
@matthew-carroll I think this is valid, let's discuss in our next call. There should be a way to define an area (larger than the actual text) that reacts to clicks to place the cursor at the last position of the actual text. This is the case in e.g. Apple Notes.

**Comment by osaxma** [comment]
_comment  originally posted at #376 (modified)_

## Reproduction Steps
Take the following editor as an example:

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

class SimpleEditor extends StatefulWidget {
  @override
  State<SimpleEditor> createState() => _SimpleEditorState();
}

class _SimpleEditorState extends State<SimpleEditor> {
  late final document = MutableDocument(nodes: [ParagraphNode(id: '1', text: AttributedText())]);
  late final DocumentEditor editor = DocumentEditor(document: document);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(30.0),
        child: Container(
          decoration: BoxDecoration(border: Border.all(color: Colors.black, width: 10)),
          child: SuperEditor(
            editor: editor,
          ),
        ),
      ),
    );
  }
}
```

Which will render the following: 
<p align="center"><img width="500" alt="Screen Shot 2022-01-17 at 12 26 23 PM" src="https://user-images.githubusercontent.com/46427323/149743090-ae12f25e-f59d-4bd0-9317-6271760e09b8.png"></p>

As seen in the photo above:
- Everything inside the black borders is SuperEditor widget.
- The grey area is the `TextComponent` (color manually added for presentation purposes). 


To Reproduce:
- Make sure SuperEditor does not have focus (i.e. click outside the black borders to unfocus). 
- Moving the pointer above the editor does not indicate it's an editor (i.e. showing a cursor like in most editors).
- Tapping anywhere but the grey area, SuperEditor will gain focus but the caret will not show up.
- The user must precisely tap on the grey area in order for the caret to show up -- which is pretty tough when the entire page is white, for instance. 

## Expected Behavior:

I think upon gaining focus, SuperEditor should have an option to auto create a selection based on some strategy:
- Gesture: place the selection at the closest position to where the gesture occurred -- fallback to end of line or end of document.
- Other means (programmatically or keyboard Tab): place the selection at the previous selection before focus was lost (requires caching the selection*) -- fallback to end of line or end of document. 
 
\* Example of cached selection:

https://user-images.githubusercontent.com/46427323/149751257-5037d698-b673-4681-b1ab-aa26b6346087.mov


## Workaround
Currently I've a workaround using the following pseudo code:

```dart
  GestureDetector(
    onTap: focusNode.hasFocus 
        ? null // to avoid conflicting with SuperEditor's gestures
        : () {
            // - move the caret to the end manually using the composer
            focusNode.requestFocus();
          },
    child: SuperEditor(
      editor: editor,
      focusNode: focusNode,
    ),
  ),
```

The approach above has few issues with conflicting gestures, and it adds a burden of both managing when the gesture should be present and using the composer to move the selection manually upon focus.

**Comment by matthew-carroll** [comment]
@bk-one @osaxma - I think the question here is the right level of control and policy. It's an easy issue to solve when we assume a Medium style UI where the whole UI is a big editor. Things get trickier when the document sits in a pane, like Superlist. It gets quite a bit trickier if we consider a column with a handful of different `SuperEditor`s in the column. Imagine something like a Facebook feed where some of the cards are little `SuperEditor`s.

We'll want to iron out how we can make this use-case easy, without reducing the places where a `SuperEditor` can be used.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros I'd like to get your opinion on this ticket.

There are 2 questions at play here: what happens on focus, and what happens when you tap somewhere in a document.

Let's forget about the focus question for now. What should happen when you tap various places in a document? This question applies whether the document is empty, or not.

We could make the entire `SuperEditor` widget tappable, and then map the user's tap to the nearest content location.

Is that something that would make sense to you? If we do that, do we need to offer other configurations? Will that policy create problems for certain use-cases?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll 
This (tap somewhere within the boundaries of the editor and place the selection closer to the tap offset) makes sense for Superlist uses `SuperEditor`.

I'm not sure what other configurations make sense, but I guess those will eventually emerge as feature requests by other developers. Supporting both policies (1. place selection only when tapping a node; 2. place selection close to the tap offset when tapping somewhere in a document), would be great.
