### ISSUE TITLE
[MacOS] Blinking Cursor consumes unreasonable amount of CPU resources

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#282]
See evidence: https://www.loom.com/share/8f5d64bede4f4891b0ccffa69dde8dd6

Easy to reproduce:
- Start the Example app on MacOS
- Have the cursor visible and blinking
- CPU usage increased unreasonably

**Comment by bk-one** [comment]
@matthew-carroll we analyzed our app to investigate the high CPU usage and tracked it down to SuperEditor. We stopped at that point, but maybe @knopp can help to give you the details he uncovered? I would like you to look into it - maybe other systems are affected as well? 
The loom and evidence posted was done using the sample app of SuperEditor (not Superlist), so it appears to be an isolated problem of SuperEditor?

**Comment by knopp** [comment]
It gets slightly worse now that there is QuickCreate window - it has a hidden focused field that keeps repainting even if window is hidden. This can however be fixed by simply unfocusing the text field as the window gets hidden.

Regarding the CPU usage, it is on my TODO list to investigate. I've experienced several times (mostly after computer wake-up) that the CPU load was way beyond expected CPU load (even with cursor blinking).

I'm not sure that this is something super editor can solve though. I assume it only triggers repaint when cursor visibility changes?

 In general Flutter engine repaints all layers on every frame, which makes blinking cursor just as heavy as any other UI update. Addressing this (partial repaints) is a work in progress. Part of it already landed ( https://github.com/flutter/engine/pull/21824 ), but it's not wired up yet.

**Comment by matthew-carroll** [comment]
Has this only been seen on Mac OS, then? Because on mobile, Flutter should not be repainting everything all the time....

**Comment by knopp** [comment]
> Has this only been seen on Mac OS, then? Because on mobile, Flutter should not be repainting everything all the time....

It's not specific the particular embedder. On every platform flutter engine rasterizes entire layer tree on every frame (some layers may be raster cached though). There is a PR for wiring up partial update for mobile platforms (https://github.com/flutter/engine/pull/25158) but I haven't had much time lately to push it through. On desktop it's even trickier since it would involve embedder API changes.

**Comment by matthew-carroll** [comment]
I turned on debug tools to show what Flutter thinks is repainting. You'll in this video that only the paragraph where the caret blinks is repainting. I think this probably confirms what @knopp said about the engine. Do either of you think that this deserves further investigation?


https://user-images.githubusercontent.com/7259036/131609821-43814b38-36ad-47ad-99d8-5581be4ae341.mov

**Comment by bk-one** [comment]
Yes, I think we cannot release an editor that consumes an unreasonable amount of CPU just because it is active. Your video is already close to the required evidence we need to file a ticket for the engine, isn't it? I see two paths forward:
- either we're doing it wrong and there is an easier or more lightweight way to display the caret, then it's on us
- the Flutter engine is by design performing the repaint as shown and there is no other way, then we should file a ticket with all the evidence to the Flutter team, and optionally propose a PR on how to solve it - if that is even possible from our position

**Comment by matthew-carroll** [comment]
That makes sense. I'm not sure what more we would show. It's still possible that it's my fault, but I think it would take the confirmation or rejection by someone with knowledge of the engine.

@knopp linked a couple PRs that are in-progress. If that work resolves the root issue, then any ticket that we file would be closed as a duplicate, because there must be some upstream tickets for those PRs, already.

**Comment by knopp** [comment]
The PRs would make cursor repaint lighter, but one of the significant issues I'm seeing here is that the cursor only blinks couple of times a second, yet it cases full 60fps repaints. I'm not seeing this with flutter text field for example (where it only triggers repaint when cursor state changes). This seems like something that could be addressed in super editor.

**Comment by matthew-carroll** [comment]
Sure, I could change the implementation. It sounds like you want to take advantage of the fact that this particular caret animation is binary: visible or invisible. In general, of course, a cursor could constantly fade in and out. It's only incidental that this one does not. But I'll look at moving the animation to a timer-based system instead of an `AnimationController` and we can see if that helps in this case.

**Comment by knopp** [comment]
For the time being I'd definitely stick with "binary" cursor :) I think on iOS the system cursor has a slight fade but I don't think that's worth it right now given the heaviness of single repaint. If not done yet, it might be worth putting cursor in repaint boundary, which puts the cursor in a separate engine layer. Which may cause the text behind it to be raster cached after couple of updates.

The PR in progress would help, but repainting everything 3-4 times per second for now instead of 60 would probably help even more.

**Comment by matthew-carroll** [comment]
Here's a video with the `Timer` adjustment. It will probably blow up tests because `Timer`s always seem to outlive the test and cause an exception, but we're very light on tests right now anyway. I'll put up a PR with this change so that you two can try it out.

When the only thing happening is a blinking cursor, my CPU usage is back down to about 2% (down from about 20%). Selection dragging seems to spike it again, at least momentarily.


https://user-images.githubusercontent.com/7259036/131632406-0585ce0d-78a7-49cb-ae32-3776a70e220b.mov

**Comment by knopp** [comment]
That seems a lot better. Selection dragging has to repaint more often, so increased CPU load is somewhat expected there. Given that the editor presumably results in one flutter engine layer (`DisplayListLayer`) not even the partial repaint PR would completely solve this. Are you triggering repaint when selection actually changes, or on every mouse event? If it's the former then it is likely as good as it's going to get for now.

**Comment by matthew-carroll** [comment]
I'd have to dig around to be sure, but I'm pretty sure I'm only notifying listeners when the selection value changes, regardless of mouse position.
