### ISSUE TITLE
Example App: Text Alignment (Left, Right, Center)

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#33]
**Context of use:** Change Block Layout
**Primary Actor:** User
**Triggers:** User selects text

**Main Success Scenario:**
- [ ] 1. The user selects some text
- [ ] 2. The system displays a popup above the selected text (see screenshot below)
- [ ] 3. The user selects the Text Alignment dropdown to open the options
- [ ] 4. The option of the current text alignment of this paragraph is highlighted (left in the example below)
- [ ] 5. and chooses `right`
- [ ] 6. The whole paragraph is rendered right-aligned, the popup and the selected text is removed
- [ ] 6a. If the user selects `center` the paragraph is centered

**Screenshots:**

![alignment](https://user-images.githubusercontent.com/37401/105712746-8760f980-5f1a-11eb-8975-72c6f31545e2.jpg)

![alignment-2](https://user-images.githubusercontent.com/37401/105712750-892abd00-5f1a-11eb-9ace-de3ecac88db1.jpg)

**Comment by matthew-carroll** [comment]
This looks like a product ticket rather than a package ticket. super_editor might be missing some features that are needed for this goal, but I don't think we want to bake in a floating menu of any kind.

@salihgueler let's figure out what Superlist needs super_editor to do so that Superlist can achieve this product goal.

**Comment by matthew-carroll** [comment]
Ignore my previous comment. This is a ticket for the example app.
