### ISSUE TITLE
Latest published version (0.1.0) fails to build 

### ISSUE THREAD

**Issue by jonaird** [superlistapp/super_editor#332]
The latest published version fails to build because of its reliance on `RenderEditable.nextCharacter` and `RenderEditable.previousCharacter` in `TextLayout.getCharacterStartBounds` and `TextLayout.getCharacterEndBounds` which [according to the docs](https://api.flutter.dev/flutter/rendering/RenderEditable/nextCharacter.html) are only visible for testing. Maybe this was a recent change?

**Comment by matthew-carroll** [comment]
I've since copied that code into `super_editor` to deal with that. Of course, we can't change the existing release.

For now, you can try depending directly on the GitHub project.

I'll look at cutting another build. The problem there is that `super_editor` depends on some things in Flutter that haven't made it to the stable channel yet. We may need to wait until the end of the year to cut a new build.

**Comment by matthew-carroll** [comment]
Note: cutting a new release is blocked on Flutter's rollout of text deltas.

**Comment by khuntia** [comment]
Hi @matthew-carroll 

I tried running demo (in example) on web, but it fails for compilation with Error: Type 'TextEditingDelta' not found. as well as many TextInputClient related issues. I believe its to do with the text deltas rollout of flutter as you mentioned here. If yes, is there a way to run the demo skipping them for now? If not, is there another version/branch of super-editor i can check which does compile with present Flutter. Thanks for the help!

Abhi

**Comment by matthew-carroll** [comment]
Due to Flutter hiding some character code that broke super_editor, the only two ways to compile right now is to be on Beta, Dev, or Master for Flutter, or be on a stable version of Flutter that's old enough to provide public access to the character code that Flutter took away. I'm not sure how many stable releases you need to go back. Maybe 2 or 3.

I expect that the next Flutter stable release will contain the deltas that we needed in super_editor.

**Comment by bk-one** [comment]
New pub.dev version is released, please re-open if there is still an issue
