### ISSUE TITLE
requestFocus does not show caret in editor when no selection is present

### ISSUE THREAD

**Issue by jhlabs** [superlistapp/super_editor#376]
To reproduce:
- Create a default `SuperEditor` instance and assign an external `FocusNode`
- Trigger the `focusNode.requestFocus()`
- Observe that no caret becomes visible in the editor

When requesting the focus of the editor through e.g. keyboard shortcuts for the first time, no caret selection appears in the editor.

I will post a PR with a possible solution to set the caret position to the end of the document when no selection is present.

**Comment by osaxma** [comment]
I believe there is a similar issue when requesting the focus using gestures. 

Take the following editor as an example:

```dart
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

class SimpleEditor extends StatefulWidget {
  @override
  State<SimpleEditor> createState() => _SimpleEditorState();
}

class _SimpleEditorState extends State<SimpleEditor> {
  late final document = MutableDocument(nodes: [ParagraphNode(id: '1', text: AttributedText())]);
  late final DocumentEditor editor = DocumentEditor(document: document);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(30.0),
        child: Container(
          decoration: BoxDecoration(border: Border.all(color: Colors.black, width: 10)),
          child: SuperEditor(
            editor: editor,
          ),
        ),
      ),
    );
  }
}
```

Which will render the following: 
<p align="center"><img width="500" alt="Screen Shot 2022-01-17 at 12 26 23 PM" src="https://user-images.githubusercontent.com/46427323/149743090-ae12f25e-f59d-4bd0-9317-6271760e09b8.png"></p>

> Note: 
> - Everything inside the black borders is SuperEditor widget.
> - The blue grey area is the `TextComponent` (color manually added for presentation purposes). 

The issue in the example above is that the gesture must be precisely placed within the blue grey area in order for the caret to show up -- which is pretty tough when the entire page is white, for instance. 

This similar to the issue because when the user touches anywhere inside SuperEditor (except the blue grey area), SuperEditor will gain focus but it'll not show where the caret is since the selection will be `null`. 


Currently I've a workaround using the following pseudo code:
```dart
  GestureDetector(
    onTap: focusNode.hasFocus 
        ? null // to avoid conflicting with SuperEditor's gestures
        : () {
            // - move the caret to the end manually using the composer
            focusNode.requestFocus();
          },
    child: SuperEditor(
      editor: editor,
      focusNode: focusNode,
    ),
  ),
```

The approach above has few issues with conflicting gestures, and it adds a burden of both managing when the gesture should be present and using the composer to move the selection manually upon focus.

I think upon gaining focus, SuperEditor should have an option to auto create a selection based on some strategy:
- Gesture: place the selection at the closest position to where the gesture occurred, fallback to end of line or end of document.   
- Other means (programmatically or keyboard Tab): place the selection beginning of the document or end of the document (for tab, I'm not sure if Flutter's focus system has a way to detect if the user was moving forward (e.g. tab) vs backward (e.g. shift+tab)). 


---
I was gonna write this at the PR initially but I thought this is more of a description about the issue.

cc @matthew-carroll

**Comment by osaxma** [comment]
Example of cached selection:

https://user-images.githubusercontent.com/46427323/149751257-5037d698-b673-4681-b1ab-aa26b6346087.mov

**Comment by matthew-carroll** [comment]
@osaxma does the tapping issue still occur? `SuperEditor` should place the caret at whichever position is closest to the tap location.

**Comment by matthew-carroll** [comment]
FYI @angelosilvestre - I think the use-case that we're trying to support in this ticket is the ability to press `tab` and move focus into a `SuperEditor` and begin typing.
