### ISSUE TITLE
Second Click on Text Alignment option of selection controls in default example throws an exception 

### ISSUE THREAD

**Issue by osaxma** [superlistapp/super_editor#380]
Pretty much the title and this video shows the issue and reproduction (it's in the latest main): 

https://user-images.githubusercontent.com/46427323/147884349-631902bf-c6c3-4167-babe-e38372f4c2c0.mov

**Comment by osaxma** [comment]
If the selection controls for the examples will have a rework, these related issues could be considered too:

- first option is hidden behind the floating bar:
<img width="751" alt="Screen Shot 2022-01-02 at 8 42 32 PM" src="https://user-images.githubusercontent.com/46427323/147884463-11d6b2ef-f072-4a4b-b399-d466e84a19b7.png">

- the floating bar is outside the app window:
<img width="791" alt="Screen Shot 2022-01-02 at 8 41 56 PM" src="https://user-images.githubusercontent.com/46427323/147884474-051eb413-ee5d-48ba-bdce-e38f53e243d3.png">

**Comment by angelosilvestre** [comment]
The issue was happening when clicking on the `DropdownButton` while the dropdown list is visible. 

After the fix for https://github.com/superlistapp/super_editor/issues/670, the dropdown list is displayed above the button, so it should not be possible to click on the `DropdownButton` a second time.

I tested it manually and wasn't able to reproduce the issue. I'm going to close this.
