### ISSUE TITLE
Spike: Investigate inline widget support

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#390]
Super Editor needs to support inline widgets.

Examples:
 * Typing a pattern might convert into a small icon, e.g., `:fire:` -> :fire: - when it's an emoji, an inline widget isn't needed, but the desired image might be a small bitmap
 * A checkmark or progress indicator at the end of a line. Positioning such a visual in a `Row` won't work because if the text is multiline, we don't want the earlier rows of text to leave any space at the end of the line. ![](https://whimuc.com/396Z6f4vT9FDieggyi2Tm3/8is26mxUAvMtLj.png)
 * Avatar images that replace a given user name, e.g., converting @SuprDeclarative to a small avatar
 * Inline code (I'm not sure if this should be solved with an inline widget or styled text with a custom painter behind it)

These use-cases involve multiple, independent concerns:
 * Rendering arbitrary content within text
 * Adjusting `AttributedText` and its associated rendering behavior to allow for non-text content
 * Selection dynamics: 
   * What happens when the user taps somewhere in the inline widget? 
   * What happens when the user drags part of the way into the inline widget? 
   * What happens when the user drags across the inline widget? 
   * What happens when the user presses `backspace` at the end of the inline widget? 
   * What happens when the user presses `delete` at the beginning of the inline widget? 
   * What happens when the user presses arrow keys into/out of the inline widget? 

This ticket is a spike to investigate the available level of control that Flutter provides for rendering inline widgets and how much access we have to the inline widgets' bounds an other properties. By the end of this ticket, we should be in a position to propose tacit answers to the questions above.

**Comment by pulyaevskiy** [comment]
> Inline code (I'm not sure if this should be solved with an inline widget or styled text with a custom painter behind it)

There is one limitation to the custom painter behind inline code. I believe there is no way to add some extra padding around the inline code span to allow room for the custom decoration (background and/or border).

Ideally, it would be nice if TextSpan allowed to specify such customizations, e.g. additional padding around the span and BoxDecoration to paint behind it. I looked at the C implementation which is almost 1-1 based on SkiaText and such customizations are not supported there.

So WidgetSpan is probably the only available option here. Which should work fairly well for the inline embed case where embedded content is indivisible and always 1 character long. Reporting text metrics using TextPainter should work out of the box. But for inline code it'll require a bit more work since user generated events (hitTest, selection, cursor movement) will need to be propagated down to the inline widget and back to the user.

**Comment by matthew-carroll** [comment]
@pulyaevskiy you might be right about that. How would one handle an inline code sample that needs to break across lines? A `WidgetSpan` is forced to render a single block within the text, right?

**Comment by pulyaevskiy** [comment]
Oh, you're right. This was actually the reason I gave up trying to fit inline code in WidgetSpan.

So, yeah, not a lot of options here in the end. It is worth exploring if C implementation of Flutter's Paragraph can be extended to allow extra (horizontal) padding around a text span.

**Comment by matthew-carroll** [comment]
Another possibility is for Flutter to support another type of Widget span, or perhaps a `RenderSpan` that allows the span to construct multiple rectangles of content. But either way, it probably needs Flutter's intervention.

**Comment by matthew-carroll** [comment]
Here's a write-up for this ticket: https://github.com/superlistapp/super_editor/discussions/392
