### ISSUE TITLE
`DefaultDocumentLayout.showCaret` is constrained by `gestureMode == DocumentGestureMode.mouse`

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#419]
Not sure if this intentional or a leftover from the initial work to support mobile.

Currently we check `ComponentContext.showCaret` in a component builder, which works as expected on macOS, but on mobile it always returns `false`.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros can you frame the issue in terms of what is happening, that shouldn't happen, or what isn't happening, that should happen?

**Comment by miguelcmedeiros** [comment]
@matthew-carroll 

We have component builder for a task which aside from the other task gimmicks, returns a `TextWithHintComponent` for the title of the task. On desktop, the caret is only rendered when `TextWithHintComponent.showCaret` is `true`. In this case, we get this boolean as shown in the [demo for using text component with hint](https://github.com/superlistapp/super_editor/blob/main/super_editor/example/lib/demos/components/demo_text_with_hint.dart#L156):
```
  final showCaret = componentContext.showCaret && componentContext.nodeSelection != null
      ? componentContext.nodeSelection!.isExtent
      : false;
```

The same logic does not work on mobile since `componentContext.showCaret` is always `false`.

After opening this issue (and associated PR) I noticed something else. If on mobile we set `TextWithHintComponent.showCaret` to `true` based only on whether the node is selected, then we get 2 carets. I'm guessing one comes from the mobile `IOSDocumentTouchInteractor` (or `AndroidDocumentTouchInteractor`) and another one from `TextWithHintComponent` (`SuperSelectableText` under the hood). Here's a quick loom on how I reproduce it using super_editor demo app: https://www.loom.com/share/4b81f53d9e6044e4a12021defd166a5f

With these insights we might close this issue and open 2 separate issues which addresses the following:
1. It should not be possible to render 2 carets
2. It should be possible to customise the theme of the caret on mobile (similar to what it's possible on desktop), like the width and color, as well as the mobile drag handles 

What do you think?

**Comment by matthew-carroll** [comment]
The way `super_editor` handles carets on desktop and mobile are different, by design.

On desktop, each component is asked to render a caret. This was the most versatile approach and it worked fine for desktop up to this point.

On mobile, carets are indistinguishable from drag handles, and those drag handles need to be able to move anywhere in the document. They can't be confined to any single component. Therefore, on mobile, we turn off component caret rendering and we switch to an overlay. The way that we turn off component caret rendering is by using that condition that you referenced in the original ticket description.

> It should not be possible to render 2 carets

Ironically, your team doesn't want this to be true at all! If you want to show other users working in the same document, then you definitely want the ability to render 2+ carets. You just don't want that to happen when it shouldn't.

> It should be possible to customise the theme of the caret on mobile (similar to what it's possible on desktop), like the width and color, as well as the mobile drag handles

Yeah, a lot of things in the mobile controls should be theme-able, but aren't. However, I think this is completely distinct from what we're discussing here.

As for this situation, do your task items implement the `DocumentComponent` contract? https://github.com/superlistapp/super_editor/blob/main/super_editor/lib/src/core/document_layout.dart#L82

The `DocumentComponent` API is how the document layout maps between logical caret locations and visual caret locations. On mobile, your tasks need to defer to the shared caret solution, because any other approach would make it impossible for the user to drag the caret from the middle of your task, up to the middle of a paragraph.

**Comment by miguelcmedeiros** [comment]
> As for this situation, do your task items implement the DocumentComponent contract?

Nope, we don't have a custom `DocumentComponent` for our task items. As mentioned before, have a component builder that returns a `TextWithHintComponent`.

Thanks to your explanation I now get this difference between mobile and desktop on how the caret is handled. That being said, other developers might make the same wrong assumption that I made.

Closing this ticket, since it seems to behave as expected.
