### ISSUE TITLE
Demo Website: the content in the editor exceeds the editor space

### ISSUE THREAD

**Issue by matthew-carroll** [superlistapp/super_editor#462]
On the demo website, adding content vertically causes the content to exceed the white space for the editor. The user ends up typing down into the page.

superlist.com/SuperEditor

Instead, when the content reaches the bottom of the white space, the editor should constrain the vertical height of the content, and the document should scroll in the white space.

**Comment by roughike** [comment]
I took a look at this, and this might be a regression in SuperEditor. Something that was previously working is not working anymore.

Here's a minimal example (replacing [these lines in the example editor](https://github.com/superlistapp/super_editor/blob/04634046f9ffbef4be1e4c548f5c767ce096ac93/super_editor/example/lib/demos/example_editor/example_editor.dart#L282-L292)) that reproduces the error:

```dart
@override
Widget build(BuildContext context) {
  return SingleChildScrollView(
    child: Column(
      children: [
        ...List.generate(5, (_) => const Text('scrolly scrolly')),
        SizedBox(
          // The 1800 here gives enough space that the editor doesn't crash
          // due to overflow straight from the get-go. Create a couple of newlines
          // manually and the crash will happen.
          height: 1800,
          child: _buildEditor(),
        ),
        ...List.generate(30, (_) => const Text('scrolly scrolly')),
      ],
    ),
  );
}
```

This is pretty much a simplified version of what we're trying to do with the website. This used to work, but doesn't work anymore.

The problem happens when trying to wrap SuperEditor with a scrollable area (such as `SingleChildScrollView`) and trying to constrain the height of SuperEditor at the same time. 

Just wrapping SuperEditor with a scroll view but without constraining the height works fine. Likewise, only constraining the height of SuperEditor without wrapping it in a scroll view also works. The overflow exception only happens when doing both at the same time.

**Comment by agenthesh** [comment]
Was trying to figure this one out. The problem seems to be that the height of the Column in SingleColumnDocumentLayout is restricted, whereas the children (Document elements essentially) are unrestricted. 

In [SingleColumnDocumentLayout](https://github.com/superlistapp/super_editor/blob/e545c895a08ff367a183822e32525d996e409389/super_editor/lib/src/default_editor/layout_single_column/_layout.dart#L499-L510) changing the build method to wrap a single child scroll view around the column seems to help. Doing this preserves the other behaviors (within a ScrollView, within a ConstrainedBox), and fixes the combined issue as well. All tests have passed as well. Not sure if this is an efficient/the right solution.

**Comment by matthew-carroll** [comment]
Update: I noticed that the mobile document overlay control goldens are broken (we're not currently running goldens in CI). When I inspected the golden failures, the test documents were no longer vertically centered. I put a border around the document and found that the document was expanding to fill the space. These golden failures might be caused by the same issue that's effecting the demo site.

**Comment by bk-one** [comment]
@matthew-carroll can we please fix this?

**Comment by matthew-carroll** [comment]
@bk-one Is this more important than all the other priorities?

**Comment by matthew-carroll** [comment]
@angelosilvestre - This is the ticket I was referencing. If you feel like this is something you can tackle, let me know, and I'll assign it to you.

**Comment by angelosilvestre** [comment]
@matthew-carroll I can take a look into that

**Comment by angelosilvestre** [comment]
@matthew-carroll Wrapping the `FeaturedEditor` with a `SingleChildScrollView` and moving the `BoxDecoration` up in the tree solves the issue. 

Should I take a look into `SuperEditor` or is this an acceptable solution?

**Comment by angelosilvestre** [comment]
After this changes:

https://user-images.githubusercontent.com/7597082/169427441-684228e3-3fa6-4b97-8624-23dc1d72ffae.mp4

**Comment by angelosilvestre** [comment]
@matthew-carroll 

> The problem happens when trying to wrap SuperEditor with a scrollable area (such as SingleChildScrollView) and trying to constrain the height of SuperEditor at the same time.

The interactor (`DocumentMouseInteractor` in this case) makes decisions about how to build it's layout taking in consideration if there is an ancestor `Scrollable` in the tree, but does not check if it's height is constrained:

https://github.com/superlistapp/super_editor/blob/f180eb9ce4b6a56cee20e1b8afd29b59d0e3eb75/super_editor/lib/src/default_editor/document_gestures_mouse.dart#L859-L877

https://github.com/superlistapp/super_editor/blob/f180eb9ce4b6a56cee20e1b8afd29b59d0e3eb75/super_editor/lib/src/default_editor/document_gestures_mouse.dart#L230-L231

Wrapping `_buildCursorStyle` with a `LayoutBuilder` we can check if the height is constrained `(constraints.maxHeight < double.infinity)` and update the behavior based on that. On Android and iOS the problem is similar.

Do you think that's the right approach?

**Comment by matthew-carroll** [comment]
I'd like to avoid `LayoutBuilder`s when they're not absolutely necessary. What is it that you want to do inside of the `LayoutBuilder`? Can you start by writing a test with the minimum configuration needed to cause this bug?

**Comment by angelosilvestre** [comment]
The `LayoutBuilder` is just to get the `BoxConstraints`. I could get the constraints from the `RenderBox` and avoid the `LayoutBuilder`

I will do some tests

**Comment by matthew-carroll** [comment]
But what do you intend to do, once you get the `BoxConstraints`?

**Comment by angelosilvestre** [comment]
I will check if we have a `maxHeight` constraint and, if so, behave as if we are not inside a scrollable widget. I tested the demo website with that change and it behaves correctly
