### ISSUE TITLE
Need to use `DeepCollectionEquality` for hash as well.

### ISSUE THREAD

**Issue by ltOgt** [superlistapp/super_editor#480]
I just fixed a bug in my own projects that was caused by using a VsCode plugin that generated `equals` and `hashCode`.

For `List` etc it uses `DeepCollectionEquality` inside `equals`, but uses the normal `hashCode` of lists inside `hashCode`.

This will mean that these objects can not be used reliably as keys in maps for example.

```dart
@override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is FileTreePath && listEquals(other.myList, myList);
  }

  @override
  int get hashCode {
    // Used to be: "return myList.hash;"
    final listHash = const DeepCollectionEquality().hash;
    return listHash(myList);
  }
```

While searching my code base for instances of this bug if found that `super_editor` inside my external packages might have the same issue:

https://github.com/superlistapp/super_editor/blob/354a86fa0b5dc2e7c70d17dc3cb8a403683cd8fc/super_editor/lib/src/core/document_editor.dart#L325

https://github.com/superlistapp/super_editor/blob/354a86fa0b5dc2e7c70d17dc3cb8a403683cd8fc/attributed_text/lib/src/attributed_spans.dart#L903

While you might not be using the same flawed plugin I have used, and while it might not be an actual issue for you, i thought id point this out real quick.

Have a nice day 👋

**Comment by matthew-carroll** [comment]
Thanks for letting us know. We'll take a look.

**Comment by faithoflifedev** [comment]
Hi @ltOgt ,

I took a look through the code in both of the files you identified.  First:
https://github.com/superlistapp/super_editor/blob/354a86fa0b5dc2e7c70d17dc3cb8a403683cd8fc/super_editor/lib/src/core/document_editor.dart#L320-L328

The `hashCode` is not using `DeepCollectionEquality`

And it's the same for the second case:
https://github.com/superlistapp/super_editor/blob/354a86fa0b5dc2e7c70d17dc3cb8a403683cd8fc/attributed_text/lib/src/attributed_spans.dart#L902-L910

Both code instances follow the recommended practice outlined by:
[lang.github.io - hash_and_equals](https://dart-lang.github.io/linter/lints/hash_and_equals.html#:~:text=Every%20object%20in%20Dart%20has,be%20overridden%20to%20maintain%20consistency.)

**Comment by matthew-carroll** [comment]
@faithoflifedev can you point to the specific place that says the `hashCode` shouldn't be adjusted for the deep collection equality? I didn't see that in the provided link...

**Comment by faithoflifedev** [comment]
@matthew-carroll , I felt it was implicit in the description and example.  

It's my understanding that the potential bug comes from using either a `MutableDocument` or `AttributedSpans` objects as keys in a `Map` due to the fact that the `hashCode` getter is used as part of the `Map` key generation. 

In brief, if it's agreed that two `MutableDocument` instances with the same content should be considered to not be `identical()` which is shown in the code, then those two `MutableDocument` objects should act as independent keys.  Since the code currently creates the `hashCode` results for the two referenced objects based on a `List` then the resulting `hashCode` for each object instance will be unique.

If my assumption that instances with the same content should be considered unique in a `Map` is incorrect then the implementation of `hashCode` will need to change.

**Comment by matthew-carroll** [comment]
@faithoflifedev - Ok, so the question is whether we want `Document`s and `AttributedText`s to be de-duplicated in a `Set` or `Map` when their content is equivalent. For `Document`s we definitely don't want that. For a moment I thought `AttributedText` would make sense to do that, but `AttributedText` is mutable, so that's probably not a good idea. We may create an immutable version of `AttributedText`. At that point I think it would make sense to make this change.

I'm going to close this issue as "won't do". Thanks.
