### ISSUE TITLE
Extent selection position is incorrect when SuperEditor is placed inside a CustomScrollView

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#496]
Steps to reproduce:
* In "Sliver Demo Editor", select some text and move the selection extent

Expected: selection is painted from the base position till the extent position (close to cursor) 
Actual: extent position is not correct
![ezgif com-gif-maker-10](https://user-images.githubusercontent.com/31278849/160028330-d80c50fb-0108-4882-8057-695ae2d09a32.gif)

**Comment by agenthesh** [comment]
So I was doing a bit of testing for this issue, and it’s a really weird one. 

Basically the extent offset (as mentioned by @miguelcmedeiros) is calculated incorrectly when there is an ancestor ScrollView. The extent offset is grows exponentially as the size of the text in the editor increases (and thus the selection grows as well). 

For example, with the default text in the editor, if we apply an addition of Offset(0, 300) to [Line 547](https://github.com/superlistapp/super_editor/blob/e545c895a08ff367a183822e32525d996e409389/super_editor/lib/src/default_editor/document_gestures_mouse.dart#L547), the offset is now correct and the selection seems fine (if you select somewhere in the middle of the text). The offset grows as the scroll position grows. 

After some testing, I found that [this function](https://github.com/superlistapp/super_editor/blob/e545c895a08ff367a183822e32525d996e409389/super_editor/lib/src/default_editor/document_gestures_mouse.dart#L217-L225) is the one responsible for this behavior. It seems that while calculating the correct offset for the autoscrolling behavior, it produces a bug for the selection. More specifically, the `interactorBox.localToGlobal ` is the one messing up here. 

I fixed this by creating a new function which calculates the offset for selection only by converting the interactorOffset to the local viewport offset. This makes more sense as we only care about the viewportOffset for the selection (not the Scrollable offset). 

Fixed behavior can be seen below: 
![ezgif-2-e36e0912cb](https://user-images.githubusercontent.com/55655058/160258503-3d80c154-d0e8-44b9-8ddd-bd0136bc98d1.gif)

**Comment by matthew-carroll** [comment]
@agenthesh thanks for looking into this. I'll take your description and see what I can put together for a fix. If you have any great ideas writing effective tests for this, without a whole lot of complexity, please let me know.

**Comment by matthew-carroll** [comment]
@agenthesh FYI - I tried making the same change that's in your "Selection fix within a SliverScrollView" commit that's linked above, and it didn't seem to have any impact on the sliver demo in the example app. The scroll position is still off. Was there more to your suggested fix?

**Comment by agenthesh** [comment]
Sorry, I did try to write tests for it, but I couldn't get anything concrete together for it. And yeah, tested it again after pulling your changes, and it's stopped working. On a maybe related note: I cannot seem to debug the code anymore after pulling your changes. Do you know what the cause could be? Seems to be related to this as well

**Comment by matthew-carroll** [comment]
@agenthesh I've been making changes to project dependencies to make the new mono repo work. Unfortunately, every attempt solves one problem and creates another. At the moment, in my local repo for development, I changed the pubspec dependencies in `super_editor_markdown` and the `super_editor` example app to use relative paths, instead of the Git paths.

The problem with the Git paths is that they're using whatever is on GitHub, which obviously doesn't have any of your local changes. Therefore, you might make changes locally and they don't seem to do anything, and that's why.

Obviously, we still need to do something about these references, but for now that path change is the best I've come up, locally.

Please let me know if that unblocks you.

**Comment by matthew-carroll** [comment]
I think I've confirmed that the root cause of this issue are the changes I made in this PR: https://github.com/superlistapp/super_editor/pull/450

By reverting those changes, the embedded scrolling seems to work OK, but it breaks regular autoscrolling again. So I need to figure out what the correct original solution should have been.

**Comment by matthew-carroll** [comment]
I believe I've solved the problem, though I'm still not entirely sure why the fix is necessary. I'm going to experiment with creating some tools to help visualize scrolling for debug purposes, and also possibly break the auto-scroller away from the doc selection. I'll aim to have a PR up sometime tonight, regardless of my progress on tooling.
