### ISSUE TITLE
Potential bug in the `CaretBlinkController` implementation

### ISSUE THREAD

**Issue by mrverdant13** [superlistapp/super_editor#523]
I am reviewing the `super_editor` repo to get familiar with it, and I have found a couple of potential issues with the `CaretBlinkController` in the following places:

- https://github.com/superlistapp/super_editor/blob/main/super_text/lib/src/caret.dart#L299-L302
  Where a `notifyListeners` call is missing after setting `_isVisible` to `true`.

  ```dart
  void stopBlinking() {
    _isVisible = true; // If we're not blinking then we need to be visible
    _stopTimer();
  }
  ```

- https://github.com/superlistapp/super_editor/blob/main/super_text/lib/src/caret.dart#L311-L326
  Where a `notifyListeners` call is also missing after setting `_isVisible` to `true`.

  ```dart
  /// Clients should call this method whenever the caret moves within
  /// the content so that the caret is made fully opaque and the blink
  /// timer restarts.
  void onCaretMoved() {
    // Immediately make the caret visible whenever the position
    // changes, e.g., when the user adds/removes a character.
    _isVisible = true;

    _timer?.cancel();

    if (!_isBlinkingEnabled) {
      return;
    }

    _startTimer();
  }
  ```

**Comment by matthew-carroll** [comment]
@angelosilvestre can you investigate and fix this ticket? I recommend writing one or more failing unit tests for `BlinkController` and then making them pass.

FYI, the blink controller has moved since this issue was opened. It's now here: https://github.com/superlistapp/super_editor/blob/main/super_text_layout/lib/src/infrastructure/blink_controller.dart

**Comment by angelosilvestre** [comment]
@matthew-carroll Sure
