### ISSUE TITLE
[SuperEditor] Drag to select skips one character in the upstream direction

### ISSUE THREAD

**Issue by jmatth** [superlistapp/super_editor#549]
When creating a text selection in the upstream direction with the mouse, the selection base will start one character further upstream than expected. See the below video for a couple examples:

https://user-images.githubusercontent.com/1316184/167518847-9ce9baae-b543-4d26-bba6-16910809a8e3.mov

I tracked the cause down to the the following line in [`text.dart`](https://github.com/superlistapp/super_editor/blob/cd0efedfd835b65ce47ce668665cd6444c98c69c/super_editor/lib/src/default_editor/text.dart#L430-L444)

```dart
    // Rework the textPosition so that it reports a "downstream" affinity because
    // the editor doesn't support "upstream" positions, yet.
    //
    // Applying the "-1" to switch from upstream to downstream works everywhere, except
    // when the position is at the very end of the text. In that case, we leave the offset
    // alone.
    return TextNodePosition.fromTextPosition(textPosition.affinity == TextAffinity.downstream
        // The textPosition is already "downstream", leave it alone.
        ? textPosition
        // The textPosition if "upstream", adjust it to become "downstream", unless
        // the position sits at the very end of the text.
        : TextPosition(
            offset: textPosition.offset < widget.text.text.length ? textPosition.offset - 1 : textPosition.offset,
            affinity: TextAffinity.downstream,
          ));
```

Revising that code to always use `textPosition` without any modifications fixes the drag to select issue but presumably breaks other forms of selection elsewhere in the codebase (though no tests fail).

**Comment by matthew-carroll** [comment]
The first step here is probably to write an exhaustive set of tests that tap and drag for text selection. Then we can adjust this behavior and see what happens to the tests.

At first glance, the `- 1` looks correct, because the `- 1` is only applied when the incoming `TextAffinity` is `upstream`. An `upstream` position at `x` is the same as a downstream position at `x - 1`. This may be a red herring, and the root cause is somewhere else entirely.

**Comment by matthew-carroll** [comment]
What happens when you look up offsets from a `RenderParagraph`? We don't use Flutter `TextField`s in Flutter, so to the extent that those text fields are massaging the `TextPosition`, we may or may not be doing that in `super_editor`. However, `super_editor` relies heavily on `RenderParagraph` for mapping to/from `TextPosition`s.

So if you pass the same `TextPosition` into `RenderParagraph`, one with `upstream` and another with `downstream`, do you get the same `Offset` returned for that position?

**Comment by jmatth** [comment]
> So if you pass the same TextPosition into RenderParagraph, one with upstream and another with downstream, do you get the same Offset returned for that position?

Yes. Test case:

```dart
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('RenderParagraph', () {
    final renderParagraph = RenderParagraph(
      const TextSpan(text: 'abcdefg'),
      textDirection: TextDirection.ltr,
    );
    renderParagraph.layout(const BoxConstraints(
      minWidth: 300,
      maxWidth: 300,
      minHeight: 100,
      maxHeight: 100,
    ));

    const downstreamPosition =
        TextPosition(offset: 3, affinity: TextAffinity.downstream);
    final upstreamPosition = TextPosition(
        offset: downstreamPosition.offset, affinity: TextAffinity.upstream);
    expect(
      renderParagraph.getOffsetForCaret(downstreamPosition, Rect.zero),
      renderParagraph.getOffsetForCaret(upstreamPosition, Rect.zero),
    );
  });
}
```

Output: 
```
$ flutter test -r expanded
00:00 +0: RenderParagraph
00:00 +1: All tests passed!
```

**Comment by matthew-carroll** [comment]
Ok, thanks. We'll need to re-evaluate all of our usages of `TextPosition` throughout `super_editor`.
