### ISSUE TITLE
Allow custom inline nodes

### ISSUE THREAD

**Issue by bk-one** [superlistapp/super_editor#66]
_Disclaimer:_ This ticket describes Superlist specific behavior. It is expected to be split into requirements for the editor package and application-specific parts. The application-specific parts can be handled by the Superlist crew, we just need the required changes and a documentation or sample application on how to add custom nodes as described.

As a user I want to be able to tag a co-worker within a paragraph (or any text). While typing regular text, I can trigger a drop-down to select a co-worker by using a special character, the @-Symbol. The behavior is similar to the behavior in this editor.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/37401/117114644-68c99480-ad8c-11eb-8b05-1b874fc10ba7.gif)

This consist of two parts:
 * While editing I should be able to trigger the drop-down, limit the options while typing and auto-complete on cursor movements or with return. The options in the dropdown are all on application level of course.
 * After completing the editing part, the selected user should be rendered in an application-specific way, in this case linking to a resource (see below, ignore the popup).

While this is an actual requirement, it's also just one of many for custom in-line auto-complete and rendering that Superlist will require. Other examples include:
 - Linking to a specific task or list within the application
 - Setting metadata (e.g. labels) directly from within the text editor
 - Term recognition (e.g. times) to identify specific words, e.g. `tomorrow` or `next week` and render those differently

We will further need rendering on block-level later on as well, not only inline. 

**Screenshots:**

<img width="558" alt="Screen Shot 2021-05-05 at 10 28 40" src="https://user-images.githubusercontent.com/37401/117114961-c231c380-ad8c-11eb-93ba-46b21d810443.png">

**Comment by matthew-carroll** [comment]
@bk-one @salihgueler I think we should accumulate a set of use-cases for this ticket. The reference to "inline nodes" implies a particular logical document structure, rather than use-case goals.

I understand that there is some kind of goal here in which text patterns are recognized and then some kind of action is taken. I think we need quite a bit more detail before this is actionable.

**Comment by bk-one** [comment]
updated the description, I hope this is more clear now

**Comment by ericmartineau** [comment]
I came here to request this as well.  My use case is very similar to the `@user` autocompletion though I would like to also add an image inline with the text (using WidgetSpan along with the TextSpans). This would require, at a minimum, some ability for an `Attribution` to participate in the process of converting text into `InlineSpan` instances.

I'm new to this library, so there may be an easy way to accomplish what I'm after as well.

**Comment by matthew-carroll** [comment]
@ericmartineau can you describe why user autocompletion requires inline widgets? Also, what kind of images are you trying to embed within the text?

**Comment by kulny** [comment]
This is similar to a feature that I would like to have as well. Inline text replaced with an interactable (gesture detection) Widget-esque object, similar (if not functionally identical) to extending Flutter's TextEditingController to override buildTextSpan so that specific text can be replaced with a WidgetSpan. This also ideally provides a way to create inline onTap interactions from text which is replaced as the user adds it when a specific string is added to the controller.

**Comment by BazinC** [comment]
> @ericmartineau can you describe why user autocompletion requires inline widgets? Also, what kind of images are you trying to embed within the text?

@matthew-carroll we have the same challenge. We would like to represent custom inlines (not text with style).
e.g: "Some text with a user mention" -> Display the user mention in the ParagraphNode as a Row(children: [UserAvatar, Text(username)]. 

or the slack emoji example from:  
"text with a :custom-emoji: !" -> replace :custom-emoji: with a custom widget.

I don't see a way to achieve this with AttributedText.

**Comment by matthew-carroll** [comment]
Hi @BazinC - this remains something that we want to support. We understand that it's a valuable feature, and we also understand that for some use-cases, such as small inline images and animations, this feature feels fundamental, because web has made it so common.

There remain two major hurdles for us to implement this feature:

1. We need to determine how such content should be represented in `AttributedText`. Should such content simply have a placeholder with an ID? Should it have an entire data structure? Does `AttributedText` need to know anything about the specifics of an inline widget?

2. We need to implement flow-based layout. Flutter doesn't even support flow-based layout. We'd likely need to re-implement all of `RenderParagraph` to achieve this. I've looked into it a few times, but so far, the effort outweighs the number of requests that we receive for this feature.

That said, if any companies would like to fund this effort, we can make it a priority.

**Comment by manoletre** [comment]
In addition to the use case that both @BazinC and @ericmartineau have described, I am looking to support inline-math. 

<img width="509" alt="image" src="https://github.com/superlistapp/super_editor/assets/8203735/7e0565df-d93a-431c-b397-07219f26561f">

For that I need to somehow have custom widgets Inside a `TextComponent`- in this case a `Math.tex` widget.

**Comment by mochar** [comment]
Is this still being worked on?

**Comment by matthew-carroll** [comment]
@mochar this was never being worked on.

**Comment by mochar** [comment]
> @mochar this was never being worked on.

Ok thanks!

For others that are looking for thuis feature, I found visual editor does support it

**Comment by matthew-carroll** [comment]
Looking back at this ticket, the original goal (user tagging) has been implemented. However, there's a related concern, which is the ability to place arbitrary content within line-baed layout. To specifically track that issue, I've filed https://github.com/superlistapp/super_editor/issues/2359

I'm going to close this one in favor of the new ticket. Hopefully we can get a few clients to split funding for that issue and we can bring a new form of text layout to Flutter.
