### ISSUE TITLE
[super_editor] - Example app toolbar disappears when tapping anything with focus

### ISSUE THREAD

**Issue by zhangwb1996** [superlistapp/super_editor#689]
EDIT (Matt): I changed the title of this ticket to match what I found. I also added a comment in the thread that defines the problem.

---
When the app is running, DropdownButton doesnt contain any List of _TextType or TextAlign in the _toolbar.dart,but  the widget tree lists the DropdownButton items 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/41967295/178006051-2067952c-8746-41a3-9a19-0e2b62f06017.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/41967295/178009373-1fdbc403-17cb-44ce-91d6-48b2bd49fc61.png">

**Comment by matthew-carroll** [comment]
@zhangwb1996 can you please express the problem in terms of user functionality? What behavior do you expect? What behavior are you seeing?

**Comment by zhangwb1996** [comment]
https://user-images.githubusercontent.com/41967295/178645122-20decf60-4731-45b0-913f-6fc796d2ae5c.mp4

in this video, when i click the DropdownButton, maybe, the items of DropdownButton should hava been listed, instead the toolbar disappeared. 
And i try it in a simple and independent demo, the items are not listed and the Overlay also disappeared.

**Comment by matthew-carroll** [comment]
I've looked into this. The problem here is the same as #609, but in our fix for that we only applied the change to the URL text field. We need to apply the focus fix to the entire toolbar. I'll do that in response to this ticket.

**Comment by zhangwb1996** [comment]
Thanks a lot

**Comment by matthew-carroll** [comment]
I think we may be blocked on this issue for now. The problem is that `DropdownButton`, which is used for both selecting the node type, and selecting the text alignment, displays its dropdown in a custom `Route`. 

By displaying the dropdown in a custom route, and giving the dropdown focus, the primary focus escapes our control. We can't wrap individual dropdown items with our own `Focus` widget, either, because the item builders must return a `DropdownMenuItem` widget, specifically.

It's unclear what we're supposed to do in this situation from a Flutter API perspective. I've mentioned this issue in the conversation thread for https://github.com/flutter/flutter/issues/106923. I think we're probably blocked until that thread is resolved.

CC @miguelcmedeiros @venkatd - in case either of you have any ideas.

**Comment by matthew-carroll** [comment]
@rutvik110 I think this might be the root problem for the toolbar issue. If so, it's been blocked by Flutter for a year.

**Comment by rutvik110** [comment]
I see. So, is there something we can do here? 
Read abt ur progress on it that you've got something working with url texts, is that ready to be extensible to the whole toolbar?

**Comment by matthew-carroll** [comment]
If I remember correctly, the problem is with the dropdown button. The dropdown button internally pushes a route, and routes automatically steal focus. I don't think we have a way around that.

If that's the problem, then I don't think there's anything we can do, short of build our own dropdown button. But I'm not sure that's a good use of our time.
