### ISSUE TITLE
[super_editor] - How to serialize/deserialize into json

### ISSUE THREAD

**Issue by egnimos** [superlistapp/super_editor#718]
I want to store the document node in the form of json, but I can't able to do that, Is there any way to perform this operations

thank you :)

**Comment by SeanfvdM** [comment]
Hey @egnimos I was also wondering how to do it and after long searching to no avail. I decided to do it myself for my project after I finished that, I saw this issue.

I made it a package that should hopefully help with this issue.
[pub.dev](https://pub.dev/packages/super_editor_unofficial_helper)

**Comment by matthew-carroll** [comment]
@egnimos we don't offer any specific serializations in super_editor, because there are an infinite number of formats that developers might want to use. However, you can serialize your `Document` into any format that you'd like. You just need to loop through the nodes in the `Document` and write the relevant information to JSON, or HTML, or anything else.

We do have one format that's supported, which is Markdown. You can use this package as an example for how to serialize and deserialize your own formats:
https://github.com/superlistapp/super_editor/tree/main/super_editor_markdown

**Comment by egnimos** [comment]
@matthew-carroll, I have extended json method in each and every node and its working pretty fine,
@SeanfvdM thank you for suggesting, a package I will give it a try

**this package is really awesome**
