### ISSUE TITLE
Multiple subcomponents interaction

### ISSUE THREAD

**Issue by Jei-sKappa** [superlistapp/super_editor#774]
Add a way to add multiple subcomponents to one bigger component.
An example could be the TaskNode or the ListNodes, which both have a leading widget but it is not selectable in any way.
Expected result:

https://user-images.githubusercontent.com/46776108/188424670-297b7132-d118-44f4-abf2-067d60241527.mov

**Comment by matthew-carroll** [comment]
Can you describe why this is a super_editor concern? If you're implementing custom components, then you need to implement selection for that component.

**Comment by Jei-sKappa** [comment]
My final goal is, for example, to create a new component that is just like the Task Node in the example app; the main difference is that the CheckBox should be selectable and when copied, by selecting it, I should have something custom in the clipboard like "- [x]".
How can I do that?
Probably the best thing for this example is to use the existing TaskNode component as a starting point.
The first thing that I will do is wrap the CheckBox widget inside a BoxCompoent, and I need to pass it a key to make it selectable, but which key?
There is already a key [textKey] passed from the componentContext to the component Builder and it cannot be used in two different Components.
How can I solve this?
Keep in mind that I may have chosen a wrong path to solve this problem but unfortunately I haven’t found a different way to do it.

If I am right it's a super_editor concern to maybe provide multiple keys as needed or something else.
Thanks for your time.

**Comment by matthew-carroll** [comment]
I think that what you need to do is create your own version of `TaskComponent`, which knows how to paint a selection around the checkbox. Then, you also need to create a new `ComponentBuilder` that creates and returns your new component, instead of using the existing task component builder.

You might be able to use the existing `TaskNode`, but given that you're altering the meaning of the node selection, you may need to create your own version of `TaskNode`, too. A `TaskNode` expects a node selection of type `TextNodeSelection`. With that selection, an offset of zero means the caret should sit at the beginning of the text, but you want the caret to sit before the checkbox.

> If I am right it's a super_editor concern to maybe provide multiple keys as needed or something else.

Super Editor will only provide a single key per node. You'll need to make that work for your use-case. You may need a more sophisticated representation of selection within your node. But you shouldn't need more than one key.

I'm going to close this issue because I don't think there's anything for `SuperEditor` to do. If you run into specific bugs, or if you find a clear definition for a new feature, then please open appropriate tickets for those things.
