### ISSUE TITLE
SuperEditor does not release focus when tapping elsewhere

### ISSUE THREAD

**Issue by miguelcmedeiros** [superlistapp/super_editor#775]
Steps to reproduce:
* Place a `SuperTextField` above `SuperEditor`
* Tap on `SuperEditor` to give focus to it
* Tap on `SuperTextField` to give focus to it

Expected: focus moves from `SuperEditor` to `SuperTextField`
Actual: focus stays in `SuperEditor`

It is possible to reproduce this in `super_editor`'s demo app, by placing a `SuperTextField` above `SuperEditor` in `ExampleEditor`.

**Comment by miguelcmedeiros** [comment]
From a quick investigation, this seems to have been introduced in c866122e52b22c995630d673c2af8258722e04ec. 

Before this commit it has an issue as well, but less severe: the user needs to tap a second time in `SuperTextField` in order to get focused.

**Comment by miguelcmedeiros** [comment]
Cc @matthew-carroll @angelosilvestre

**Comment by matthew-carroll** [comment]
@angelosilvestre can you make this a top priority?

**Comment by angelosilvestre** [comment]
@miguelcmedeiros I investigated the demo app and the issue seems to be that `requestFocus` is being called when taping outside the editor.

https://github.com/superlistapp/super_editor/blob/700f0f752f9b0ac2ee05ea10e79edf97f114c26c/super_editor/example/lib/demos/example_editor/example_editor.dart#L167-L189

When the editor loses focus, the IME connection is closed, which clears the selection. In the demo, when selection changes `_hideEditorToolbar` is called, which is requesting focus again.

https://github.com/superlistapp/super_editor/commit/c866122e52b22c995630d673c2af8258722e04ec changed `SuperEditor` to restore the selection when the editor is focused, so we are in a loop of losing focus -> clearing selection -> requesting focus -> restoring selection.

In the demo app, moving `requestFocus` to inside the if statement fixes the issue. 

Is SuperList requesting focus to the editor when selection changes in a similar way to the demo app?

**Comment by miguelcmedeiros** [comment]
@angelosilvestre 
Thanks for looking into it.

Your advice solved the issue for us.

I'm leaving the issue open until the demo app is fixed.
