### ISSUE TITLE
Serialize/Deserialize HTML?

### ISSUE THREAD

**Issue by jamesdixon** [superlistapp/super_editor#902]
Hi there! Curious if anyone is working on a serializer/deserializer for HTML?

**Comment by matthew-carroll** [comment]
I don't think any of us are working on that, in part because we already support Markdown serialization and you could then turn that into HTML with a Markdown-to-HTML converter. It's a somewhat annoying half-step, but I think some of our clients have done that and they never came back to say they needed direct HTML support.

Would that work for you?

**Comment by mmasdivins** [comment]
Using a HTML to Markdown converter is not a good solutions since all the following attributes are lost:
- Background Color
- Color
- Font
- Size
- Strikethrough
- Superscript/Subscript
- Underline
- Text Alignment
- Text Direction
- Formula
- Video

**Comment by Blquinn** [comment]
In addition to many elements/attributes not being supported by markdown (without using html tags) markdown also ignores white-space. Most of the time the document that you serialize will not look the same after you de-serialize it. A xml/html/xhtml serializer will likely be more flexible, accurate and accommodate more use cases.

**Comment by matthew-carroll** [comment]
I'm going to close this ticket because we have an existing ticket that discusses HTML support: https://github.com/superlistapp/super_editor/issues/1
