### ISSUE TITLE
Please set default branch to stable if main example doesn't compile

### ISSUE THREAD

**Issue by joonsv** [superlistapp/super_editor#909]

**Comment by matthew-carroll** [comment]
@miguelcmedeiros @knopp @Jethro87 - What do you guys think about this request? I'm used to the default branch being the bleeding edge. Maybe the typical GitHub repo doesn't work that way? Thoughts?

**Comment by miguelcmedeiros** [comment]
Disclaimer: due to the project I'm working on, I'm on Flutter `stable` channel and hence I only build the example app from `stable`, so I haven't come across issues with building the example app.

All PRs target `main` and then most (except the ones that are specific to changes coming from Flutter `master`, like new lint rules, breaking changes to the API, etc.) get cherry-picked to `stable`, so the example app should run without problems from `main`. Otherwise how will any developer committing a PR be sure that the changes work (expect from automated tests). I'm curious as to why the example app does not compile from `main`. 

@joonsv can you share more information about why it fails to compile?
@matthew-carroll @angelosilvestre You are the main contributors to `super_editor`. Do you have problems compiling the example app from `main`?

I agree with @matthew-carroll perspective that `main` is usually on the bleeding edge and unless there's a strong reason to change it.

**Comment by angelosilvestre** [comment]
The `main` branch targets Flutter `master` channel. Trying to use SuperEditor `main` branch with Flutter `stable` channel will cause compilation errors.

We should use:

SuperEditor `main` -> Flutter `master`
SuperEditor `stable` -> Flutter `stable`

We should update the repo README with this information.

**Comment by Jethro87** [comment]
I think `main` should target `master` and `stable` should target `stable`. But I think this should be front and center in the README, otherwise there will be confusion going forward (as it is a bit non-standard, in my opinion, when comparing to other Flutter packages).

**Comment by matthew-carroll** [comment]
I added a couple lines to the README: https://github.com/superlistapp/super_editor/blob/main/README.md

I don't know how many people bother to read it, but at least it's there.

It sounds like `main` should continue to be our default branch, so I'm going to close this ticket. If there are additional, specific requests for clarity, please file new issues.
